"use client";

import * as React from "react";

// material-ui
import Box from "@mui/material/Box";
import CardContent from "@mui/material/CardContent";
import Grid from "@mui/material/Grid";

// project-imports

import { dispatch, useSelector } from "store";

// types
import { UserProfile } from "types/user-profile";
import MainCard from "@/components/cards/MainCard";
import CustomTable from "@/components/table/Table";
import CustomDrawer from "@/components/drawer/Drawer";
import UserDetails from "@/components/users/UserDetails";
import UserFilter from "@/components/users/UserFilter";
import { TableProvider } from "@/contexts/TableContext";
import GenericTable from "@/components/table/GenericTable";
import EndoserTableHeader from "@/components/endoser/table/EndoserTableHeader";
import EndoserTableFilter from "@/components/endoser/table/EndoserTableFilter";
import EndoserTableRows from "@/components/endoser/table/EndoserTableRows";
import EndoserDetails from "@/components/endoser/EndoserDetails";
import GemstoneTableHeader from "@/components/gemstone/table/GemstoneTableHeader";
import GemstoneTableRows from "@/components/gemstone/table/GemstoneTableRows";
import { useRouter } from "next/router";

const endoserdata = [
  {
    id: 1,
    name: "error: undefined method `/' for nil:NilClass",
    type: "Ruby",
    shape: "Princess",
    weight: 6.9,
    color_grade: "H",
    clarity_grade: "VS2",
    cut_grade: "Good",
    price: 7332.67,
    compareAtPrice: 7120.63,
    quantity: 7,
    sku: "praesent blandit lacinia erat vestibulum sed",
    status: "REJECTED",
    isFeatured: true,
    isActive: true,
    allowOffers: true,
    showOnSaleLabel: true,
    certification: "GIA",
    certificationStatus: false,
    color: "Goldenrod",
    origin: "neque vestibulum eget vulputate ut",
    transparency: "Transparent",
    images: [
      { url: "https://example.com/images/diamond1.jpg" },
      { url: "https://example.com/images/diamond1.jpg" },
      { url: "https://example.com/images/diamond1.jpg" },
    ],
  },
  {
    id: 2,
    name: "error: undefined method `/' for nil:NilClass",
    type: "Ruby",
    shape: "Princess",
    weight: 9.6,
    color_grade: "H",
    clarity_grade: "SI1",
    cut_grade: "Fair",
    price: 2851.63,
    compareAtPrice: 1247.37,
    quantity: 9,
    sku: "lacinia sapien quis libero nullam",
    status: "APPROVED",
    isFeatured: true,
    isActive: false,
    allowOffers: false,
    showOnSaleLabel: true,
    certification: "GIA",
    certificationStatus: false,
    color: "Green",
    origin: "lectus in est risus auctor",
    transparency: "Transparent",
    images: [
      { url: "https://example.com/images/diamond1.jpg" },
      { url: "https://example.com/images/diamond1.jpg" },
      { url: "https://example.com/images/diamond1.jpg" },
      { url: "https://example.com/images/diamond1.jpg" },
    ],
  },
  {
    id: 3,
    name: "error: undefined method `/' for nil:NilClass",
    type: "Ruby",
    shape: "Emerald",
    weight: 7.2,
    color_grade: "F",
    clarity_grade: "VVS2",
    cut_grade: "Poor",
    price: 488.93,
    compareAtPrice: 7839.12,
    quantity: 9,
    sku: "feugiat non pretium quis lectus suspendisse potenti",
    status: "PENDING",
    isFeatured: false,
    isActive: true,
    allowOffers: true,
    showOnSaleLabel: false,
    certification: "IGI",
    certificationStatus: true,
    color: "Crimson",
    origin: "quam nec dui luctus rutrum",
    transparency: "Translucent",
    images: [
      { url: "https://example.com/images/diamond1.jpg" },
      { url: "https://example.com/images/diamond1.jpg" },
      { url: "https://example.com/images/diamond1.jpg" },
    ],
  },
  {
    id: 4,
    name: "error: undefined method `/' for nil:NilClass",
    type: "Emerald",
    shape: "Round",
    weight: 2.9,
    color_grade: "G",
    clarity_grade: "VS2",
    cut_grade: "Good",
    price: 6608.12,
    compareAtPrice: 6138.72,
    quantity: 8,
    sku: "amet turpis elementum ligula vehicula consequat",
    status: "PENDING",
    isFeatured: true,
    isActive: true,
    allowOffers: false,
    showOnSaleLabel: true,
    certification: "IGI",
    certificationStatus: true,
    color: "Goldenrod",
    origin: "maecenas ut massa quis augue",
    transparency: "Opaque",
    images: [
      { url: "https://example.com/images/diamond1.jpg" },
      { url: "https://example.com/images/diamond1.jpg" },
      { url: "https://example.com/images/diamond1.jpg" },
      { url: "https://example.com/images/diamond1.jpg" },
    ],
  },
  {
    id: 5,
    name: "error: undefined method `/' for nil:NilClass",
    type: "Ruby",
    shape: "Round",
    weight: 2.3,
    color_grade: "J",
    clarity_grade: "I3",
    cut_grade: "Excellent",
    price: 5819.53,
    compareAtPrice: 1488.55,
    quantity: 7,
    sku: "sit amet justo morbi ut",
    status: "REJECTED",
    isFeatured: true,
    isActive: true,
    allowOffers: true,
    showOnSaleLabel: true,
    certification: "IGI",
    certificationStatus: false,
    color: "Puce",
    origin: "quam a odio in hac",
    transparency: "Opaque",
    images: [{ url: "https://example.com/images/diamond1.jpg" }],
  },
  {
    id: 6,
    name: "error: undefined method `/' for nil:NilClass",
    type: "Ruby",
    shape: "Princess",
    weight: 0.1,
    color_grade: "J",
    clarity_grade: "SI1",
    cut_grade: "Good",
    price: 7765.07,
    compareAtPrice: 8090.03,
    quantity: 5,
    sku: "venenatis turpis enim blandit mi",
    status: "PENDING",
    isFeatured: true,
    isActive: false,
    allowOffers: false,
    showOnSaleLabel: false,
    certification: "EGL",
    certificationStatus: false,
    color: "Red",
    origin: "euismod scelerisque quam turpis adipiscing",
    transparency: "Transparent",
    images: [
      { url: "https://example.com/images/diamond1.jpg" },
      { url: "https://example.com/images/diamond1.jpg" },
      { url: "https://example.com/images/diamond1.jpg" },
      { url: "https://example.com/images/diamond1.jpg" },
      { url: "https://example.com/images/diamond1.jpg" },
    ],
  },
  {
    id: 7,
    name: "error: undefined method `/' for nil:NilClass",
    type: "Ruby",
    shape: "Princess",
    weight: 9.7,
    color_grade: "F",
    clarity_grade: "VS1",
    cut_grade: "Very Good",
    price: 8011.72,
    compareAtPrice: 8634.57,
    quantity: 2,
    sku: "lorem quisque ut erat curabitur",
    status: "PENDING",
    isFeatured: false,
    isActive: false,
    allowOffers: false,
    showOnSaleLabel: false,
    certification: "IGI",
    certificationStatus: true,
    color: "Fuscia",
    origin: "sapien varius ut blandit non",
    transparency: "Transparent",
    images: [
      { url: "https://example.com/images/diamond1.jpg" },
      { url: "https://example.com/images/diamond1.jpg" },
    ],
  },
  {
    id: 8,
    name: "error: undefined method `/' for nil:NilClass",
    type: "Emerald",
    shape: "Round",
    weight: 3.8,
    color_grade: "F",
    clarity_grade: "VS2",
    cut_grade: "Fair",
    price: 9796.69,
    compareAtPrice: 2478.72,
    quantity: 3,
    sku: "nunc proin at turpis a pede",
    status: "APPROVED",
    isFeatured: false,
    isActive: true,
    allowOffers: true,
    showOnSaleLabel: true,
    certification: "GIA",
    certificationStatus: false,
    color: "Puce",
    origin: "magna bibendum imperdiet nullam orci",
    transparency: "Opaque",
    images: [
      { url: "https://example.com/images/diamond1.jpg" },
      { url: "https://example.com/images/diamond1.jpg" },
      { url: "https://example.com/images/diamond1.jpg" },
      { url: "https://example.com/images/diamond1.jpg" },
      { url: "https://example.com/images/diamond1.jpg" },
    ],
  },
  {
    id: 9,
    name: "error: undefined method `/' for nil:NilClass",
    type: "Diamond",
    shape: "Princess",
    weight: 0.9,
    color_grade: "H",
    clarity_grade: "VVS1",
    cut_grade: "Excellent",
    price: 2267.85,
    compareAtPrice: 5944.02,
    quantity: 4,
    sku: "ipsum primis in faucibus orci luctus",
    status: "REJECTED",
    isFeatured: true,
    isActive: true,
    allowOffers: false,
    showOnSaleLabel: true,
    certification: "EGL",
    certificationStatus: true,
    color: "Fuscia",
    origin: "vel dapibus at diam nam",
    transparency: "Translucent",
    images: [
      { url: "https://example.com/images/diamond1.jpg" },
      { url: "https://example.com/images/diamond1.jpg" },
    ],
  },
  {
    id: 10,
    name: "error: undefined method `/' for nil:NilClass",
    type: "Diamond",
    shape: "Oval",
    weight: 7.2,
    color_grade: "D",
    clarity_grade: "I2",
    cut_grade: "Excellent",
    price: 5351.49,
    compareAtPrice: 6630.55,
    quantity: 1,
    sku: "ut erat id mauris vulputate elementum nullam",
    status: "REJECTED",
    isFeatured: false,
    isActive: true,
    allowOffers: false,
    showOnSaleLabel: true,
    certification: "GIA",
    certificationStatus: false,
    color: "Purple",
    origin: "commodo vulputate justo in blandit",
    transparency: "Opaque",
    images: [
      { url: "https://example.com/images/diamond1.jpg" },
      { url: "https://example.com/images/diamond1.jpg" },
      { url: "https://example.com/images/diamond1.jpg" },
      { url: "https://example.com/images/diamond1.jpg" },
      { url: "https://example.com/images/diamond1.jpg" },
    ],
  },
  {
    id: 11,
    name: "error: undefined method `/' for nil:NilClass",
    type: "Diamond",
    shape: "Emerald",
    weight: 6.6,
    color_grade: "F",
    clarity_grade: "VVS2",
    cut_grade: "Excellent",
    price: 7251.56,
    compareAtPrice: 2275.17,
    quantity: 7,
    sku: "quis orci nullam molestie nibh in",
    status: "PENDING",
    isFeatured: true,
    isActive: true,
    allowOffers: true,
    showOnSaleLabel: true,
    certification: "IGI",
    certificationStatus: false,
    color: "Aquamarine",
    origin: "rhoncus aliquam lacus morbi quis",
    transparency: "Transparent",
    images: [
      { url: "https://example.com/images/diamond1.jpg" },
      { url: "https://example.com/images/diamond1.jpg" },
    ],
  },
  {
    id: 12,
    name: "error: undefined method `/' for nil:NilClass",
    type: "Ruby",
    shape: "Round",
    weight: 4.4,
    color_grade: "I",
    clarity_grade: "I3",
    cut_grade: "Good",
    price: 8372.61,
    compareAtPrice: 9272.88,
    quantity: 7,
    sku: "quam nec dui luctus rutrum",
    status: "APPROVED",
    isFeatured: true,
    isActive: true,
    allowOffers: false,
    showOnSaleLabel: false,
    certification: "AGS",
    certificationStatus: false,
    color: "Green",
    origin: "morbi ut odio cras mi",
    transparency: "Translucent",
    images: [
      { url: "https://example.com/images/diamond1.jpg" },
      { url: "https://example.com/images/diamond1.jpg" },
      { url: "https://example.com/images/diamond1.jpg" },
    ],
  },
  {
    id: 13,
    name: "error: undefined method `/' for nil:NilClass",
    type: "Ruby",
    shape: "Oval",
    weight: 3.7,
    color_grade: "I",
    clarity_grade: "VVS1",
    cut_grade: "Good",
    price: 8869.38,
    compareAtPrice: 4104.02,
    quantity: 7,
    sku: "parturient montes nascetur ridiculus mus etiam vel",
    status: "APPROVED",
    isFeatured: true,
    isActive: false,
    allowOffers: false,
    showOnSaleLabel: false,
    certification: "GIA",
    certificationStatus: false,
    color: "Crimson",
    origin: "hendrerit at vulputate vitae nisl",
    transparency: "Transparent",
    images: [
      { url: "https://example.com/images/diamond1.jpg" },
      { url: "https://example.com/images/diamond1.jpg" },
      { url: "https://example.com/images/diamond1.jpg" },
      { url: "https://example.com/images/diamond1.jpg" },
      { url: "https://example.com/images/diamond1.jpg" },
    ],
  },
  {
    id: 14,
    name: "error: undefined method `/' for nil:NilClass",
    type: "Sapphire",
    shape: "Emerald",
    weight: 9.6,
    color_grade: "J",
    clarity_grade: "I3",
    cut_grade: "Excellent",
    price: 8109.25,
    compareAtPrice: 5835.39,
    quantity: 3,
    sku: "luctus ultricies eu nibh quisque id justo",
    status: "REJECTED",
    isFeatured: false,
    isActive: true,
    allowOffers: false,
    showOnSaleLabel: false,
    certification: "EGL",
    certificationStatus: true,
    color: "Indigo",
    origin: "morbi vel lectus in quam",
    transparency: "Opaque",
    images: [{ url: "https://example.com/images/diamond1.jpg" }],
  },
  {
    id: 15,
    name: "error: undefined method `/' for nil:NilClass",
    type: "Diamond",
    shape: "Oval",
    weight: 4.5,
    color_grade: "J",
    clarity_grade: "I2",
    cut_grade: "Good",
    price: 581.47,
    compareAtPrice: 2349.76,
    quantity: 10,
    sku: "lectus vestibulum quam sapien varius ut blandit",
    status: "APPROVED",
    isFeatured: true,
    isActive: true,
    allowOffers: true,
    showOnSaleLabel: true,
    certification: "IGI",
    certificationStatus: true,
    color: "Red",
    origin: "augue vestibulum rutrum rutrum neque",
    transparency: "Opaque",
    images: [
      { url: "https://example.com/images/diamond1.jpg" },
      { url: "https://example.com/images/diamond1.jpg" },
    ],
  },
  {
    id: 16,
    name: "error: undefined method `/' for nil:NilClass",
    type: "Sapphire",
    shape: "Emerald",
    weight: 8.7,
    color_grade: "D",
    clarity_grade: "I3",
    cut_grade: "Good",
    price: 8593.45,
    compareAtPrice: 4520.24,
    quantity: 1,
    sku: "eget tempus vel pede morbi porttitor lorem",
    status: "APPROVED",
    isFeatured: true,
    isActive: false,
    allowOffers: false,
    showOnSaleLabel: false,
    certification: "AGS",
    certificationStatus: false,
    color: "Maroon",
    origin: "mattis odio donec vitae nisi",
    transparency: "Translucent",
    images: [{ url: "https://example.com/images/diamond1.jpg" }],
  },
  {
    id: 17,
    name: "error: undefined method `/' for nil:NilClass",
    type: "Sapphire",
    shape: "Oval",
    weight: 6.8,
    color_grade: "E",
    clarity_grade: "VS1",
    cut_grade: "Poor",
    price: 1281.74,
    compareAtPrice: 4445.22,
    quantity: 8,
    sku: "porttitor lorem id ligula suspendisse",
    status: "APPROVED",
    isFeatured: true,
    isActive: true,
    allowOffers: false,
    showOnSaleLabel: false,
    certification: "AGS",
    certificationStatus: false,
    color: "Yellow",
    origin: "habitasse platea dictumst morbi vestibulum",
    transparency: "Transparent",
    images: [
      { url: "https://example.com/images/diamond1.jpg" },
      { url: "https://example.com/images/diamond1.jpg" },
      { url: "https://example.com/images/diamond1.jpg" },
    ],
  },
  {
    id: 18,
    name: "error: undefined method `/' for nil:NilClass",
    type: "Emerald",
    shape: "Round",
    weight: 6.7,
    color_grade: "D",
    clarity_grade: "VVS2",
    cut_grade: "Very Good",
    price: 7881.44,
    compareAtPrice: 6564.88,
    quantity: 3,
    sku: "sit amet nunc viverra dapibus nulla suscipit",
    status: "APPROVED",
    isFeatured: false,
    isActive: false,
    allowOffers: true,
    showOnSaleLabel: true,
    certification: "IGI",
    certificationStatus: false,
    color: "Maroon",
    origin: "turpis sed ante vivamus tortor",
    transparency: "Translucent",
    images: [
      { url: "https://example.com/images/diamond1.jpg" },
      { url: "https://example.com/images/diamond1.jpg" },
      { url: "https://example.com/images/diamond1.jpg" },
      { url: "https://example.com/images/diamond1.jpg" },
      { url: "https://example.com/images/diamond1.jpg" },
    ],
  },
  {
    id: 19,
    name: "error: undefined method `/' for nil:NilClass",
    type: "Ruby",
    shape: "Round",
    weight: 3.5,
    color_grade: "I",
    clarity_grade: "SI2",
    cut_grade: "Poor",
    price: 825.53,
    compareAtPrice: 3783.57,
    quantity: 10,
    sku: "tristique in tempus sit amet sem",
    status: "REJECTED",
    isFeatured: false,
    isActive: false,
    allowOffers: true,
    showOnSaleLabel: false,
    certification: "GIA",
    certificationStatus: false,
    color: "Fuscia",
    origin: "eros vestibulum ac est lacinia",
    transparency: "Opaque",
    images: [
      { url: "https://example.com/images/diamond1.jpg" },
      { url: "https://example.com/images/diamond1.jpg" },
    ],
  },
  {
    id: 20,
    name: "error: undefined method `/' for nil:NilClass",
    type: "Diamond",
    shape: "Oval",
    weight: 2.7,
    color_grade: "D",
    clarity_grade: "SI2",
    cut_grade: "Poor",
    price: 4463.63,
    compareAtPrice: 4485.2,
    quantity: 1,
    sku: "congue eget semper rutrum nulla nunc",
    status: "PENDING",
    isFeatured: true,
    isActive: false,
    allowOffers: true,
    showOnSaleLabel: false,
    certification: "IGI",
    certificationStatus: true,
    color: "Teal",
    origin: "id ligula suspendisse ornare consequat",
    transparency: "Opaque",
    images: [
      { url: "https://example.com/images/diamond1.jpg" },
      { url: "https://example.com/images/diamond1.jpg" },
      { url: "https://example.com/images/diamond1.jpg" },
    ],
  },
  {
    id: 21,
    name: "error: undefined method `/' for nil:NilClass",
    type: "Emerald",
    shape: "Emerald",
    weight: 6.5,
    color_grade: "I",
    clarity_grade: "SI2",
    cut_grade: "Poor",
    price: 6843.31,
    compareAtPrice: 1692.8,
    quantity: 10,
    sku: "eget orci vehicula condimentum curabitur in libero",
    status: "APPROVED",
    isFeatured: false,
    isActive: false,
    allowOffers: false,
    showOnSaleLabel: true,
    certification: "IGI",
    certificationStatus: true,
    color: "Fuscia",
    origin: "nascetur ridiculus mus vivamus vestibulum",
    transparency: "Translucent",
    images: [{ url: "https://example.com/images/diamond1.jpg" }],
  },
  {
    id: 22,
    name: "error: undefined method `/' for nil:NilClass",
    type: "Emerald",
    shape: "Oval",
    weight: 6.5,
    color_grade: "H",
    clarity_grade: "VS1",
    cut_grade: "Very Good",
    price: 6524.73,
    compareAtPrice: 8345.14,
    quantity: 2,
    sku: "morbi porttitor lorem id ligula",
    status: "REJECTED",
    isFeatured: true,
    isActive: true,
    allowOffers: false,
    showOnSaleLabel: false,
    certification: "EGL",
    certificationStatus: true,
    color: "Maroon",
    origin: "cubilia curae nulla dapibus dolor",
    transparency: "Transparent",
    images: [
      { url: "https://example.com/images/diamond1.jpg" },
      { url: "https://example.com/images/diamond1.jpg" },
      { url: "https://example.com/images/diamond1.jpg" },
      { url: "https://example.com/images/diamond1.jpg" },
      { url: "https://example.com/images/diamond1.jpg" },
    ],
  },
  {
    id: 23,
    name: "error: undefined method `/' for nil:NilClass",
    type: "Ruby",
    shape: "Emerald",
    weight: 6.2,
    color_grade: "D",
    clarity_grade: "VS1",
    cut_grade: "Good",
    price: 8158.06,
    compareAtPrice: 6703.97,
    quantity: 10,
    sku: "mauris enim leo rhoncus sed vestibulum sit",
    status: "REJECTED",
    isFeatured: false,
    isActive: false,
    allowOffers: false,
    showOnSaleLabel: false,
    certification: "AGS",
    certificationStatus: false,
    color: "Mauv",
    origin: "sed ante vivamus tortor duis",
    transparency: "Transparent",
    images: [
      { url: "https://example.com/images/diamond1.jpg" },
      { url: "https://example.com/images/diamond1.jpg" },
      { url: "https://example.com/images/diamond1.jpg" },
      { url: "https://example.com/images/diamond1.jpg" },
      { url: "https://example.com/images/diamond1.jpg" },
    ],
  },
  {
    id: 24,
    name: "error: undefined method `/' for nil:NilClass",
    type: "Diamond",
    shape: "Round",
    weight: 6.9,
    color_grade: "E",
    clarity_grade: "SI1",
    cut_grade: "Poor",
    price: 9318.18,
    compareAtPrice: 6132.7,
    quantity: 2,
    sku: "tempor convallis nulla neque libero convallis eget",
    status: "APPROVED",
    isFeatured: true,
    isActive: true,
    allowOffers: true,
    showOnSaleLabel: false,
    certification: "IGI",
    certificationStatus: true,
    color: "Goldenrod",
    origin: "nec molestie sed justo pellentesque",
    transparency: "Transparent",
    images: [
      { url: "https://example.com/images/diamond1.jpg" },
      { url: "https://example.com/images/diamond1.jpg" },
      { url: "https://example.com/images/diamond1.jpg" },
      { url: "https://example.com/images/diamond1.jpg" },
    ],
  },
  {
    id: 25,
    name: "error: undefined method `/' for nil:NilClass",
    type: "Diamond",
    shape: "Emerald",
    weight: 10.0,
    color_grade: "E",
    clarity_grade: "SI1",
    cut_grade: "Good",
    price: 3941.5,
    compareAtPrice: 2423.16,
    quantity: 1,
    sku: "nibh in lectus pellentesque at nulla",
    status: "APPROVED",
    isFeatured: false,
    isActive: true,
    allowOffers: false,
    showOnSaleLabel: false,
    certification: "GIA",
    certificationStatus: true,
    color: "Pink",
    origin: "vel pede morbi porttitor lorem",
    transparency: "Translucent",
    images: [
      { url: "https://example.com/images/diamond1.jpg" },
      { url: "https://example.com/images/diamond1.jpg" },
      { url: "https://example.com/images/diamond1.jpg" },
    ],
  },
  {
    id: 26,
    name: "error: undefined method `/' for nil:NilClass",
    type: "Sapphire",
    shape: "Oval",
    weight: 9.5,
    color_grade: "G",
    clarity_grade: "VVS2",
    cut_grade: "Fair",
    price: 3621.89,
    compareAtPrice: 1944.92,
    quantity: 1,
    sku: "luctus nec molestie sed justo pellentesque viverra",
    status: "REJECTED",
    isFeatured: false,
    isActive: false,
    allowOffers: false,
    showOnSaleLabel: true,
    certification: "IGI",
    certificationStatus: false,
    color: "Orange",
    origin: "et tempus semper est quam",
    transparency: "Transparent",
    images: [{ url: "https://example.com/images/diamond1.jpg" }],
  },
  {
    id: 27,
    name: "error: undefined method `/' for nil:NilClass",
    type: "Emerald",
    shape: "Round",
    weight: 2.7,
    color_grade: "H",
    clarity_grade: "VS2",
    cut_grade: "Excellent",
    price: 4251.0,
    compareAtPrice: 2047.57,
    quantity: 4,
    sku: "sapien cum sociis natoque penatibus et",
    status: "PENDING",
    isFeatured: true,
    isActive: true,
    allowOffers: true,
    showOnSaleLabel: true,
    certification: "AGS",
    certificationStatus: true,
    color: "Mauv",
    origin: "adipiscing elit proin risus praesent",
    transparency: "Opaque",
    images: [
      { url: "https://example.com/images/diamond1.jpg" },
      { url: "https://example.com/images/diamond1.jpg" },
      { url: "https://example.com/images/diamond1.jpg" },
    ],
  },
  {
    id: 28,
    name: "error: undefined method `/' for nil:NilClass",
    type: "Emerald",
    shape: "Round",
    weight: 7.7,
    color_grade: "J",
    clarity_grade: "VS1",
    cut_grade: "Excellent",
    price: 668.45,
    compareAtPrice: 6304.11,
    quantity: 4,
    sku: "fringilla rhoncus mauris enim leo rhoncus sed",
    status: "APPROVED",
    isFeatured: false,
    isActive: false,
    allowOffers: false,
    showOnSaleLabel: false,
    certification: "GIA",
    certificationStatus: false,
    color: "Violet",
    origin: "ut massa quis augue luctus",
    transparency: "Transparent",
    images: [
      { url: "https://example.com/images/diamond1.jpg" },
      { url: "https://example.com/images/diamond1.jpg" },
      { url: "https://example.com/images/diamond1.jpg" },
      { url: "https://example.com/images/diamond1.jpg" },
    ],
  },
  {
    id: 29,
    name: "error: undefined method `/' for nil:NilClass",
    type: "Sapphire",
    shape: "Emerald",
    weight: 3.1,
    color_grade: "D",
    clarity_grade: "VVS1",
    cut_grade: "Poor",
    price: 9902.79,
    compareAtPrice: 132.61,
    quantity: 2,
    sku: "in hac habitasse platea dictumst aliquam augue",
    status: "PENDING",
    isFeatured: true,
    isActive: true,
    allowOffers: true,
    showOnSaleLabel: true,
    certification: "EGL",
    certificationStatus: true,
    color: "Purple",
    origin: "vestibulum velit id pretium iaculis",
    transparency: "Transparent",
    images: [
      { url: "https://example.com/images/diamond1.jpg" },
      { url: "https://example.com/images/diamond1.jpg" },
    ],
  },
  {
    id: 30,
    name: "error: undefined method `/' for nil:NilClass",
    type: "Ruby",
    shape: "Round",
    weight: 3.8,
    color_grade: "H",
    clarity_grade: "SI1",
    cut_grade: "Excellent",
    price: 1984.01,
    compareAtPrice: 4317.9,
    quantity: 3,
    sku: "luctus tincidunt nulla mollis molestie lorem quisque",
    status: "REJECTED",
    isFeatured: true,
    isActive: false,
    allowOffers: true,
    showOnSaleLabel: false,
    certification: "IGI",
    certificationStatus: true,
    color: "Khaki",
    origin: "est congue elementum in hac",
    transparency: "Translucent",
    images: [
      { url: "https://example.com/images/diamond1.jpg" },
      { url: "https://example.com/images/diamond1.jpg" },
      { url: "https://example.com/images/diamond1.jpg" },
      { url: "https://example.com/images/diamond1.jpg" },
      { url: "https://example.com/images/diamond1.jpg" },
    ],
  },
  {
    id: 31,
    name: "error: undefined method `/' for nil:NilClass",
    type: "Ruby",
    shape: "Oval",
    weight: 9.1,
    color_grade: "I",
    clarity_grade: "VVS2",
    cut_grade: "Fair",
    price: 259.28,
    compareAtPrice: 1394.48,
    quantity: 7,
    sku: "dapibus duis at velit eu est",
    status: "REJECTED",
    isFeatured: true,
    isActive: false,
    allowOffers: true,
    showOnSaleLabel: false,
    certification: "EGL",
    certificationStatus: true,
    color: "Maroon",
    origin: "habitasse platea dictumst maecenas ut",
    transparency: "Translucent",
    images: [
      { url: "https://example.com/images/diamond1.jpg" },
      { url: "https://example.com/images/diamond1.jpg" },
      { url: "https://example.com/images/diamond1.jpg" },
      { url: "https://example.com/images/diamond1.jpg" },
    ],
  },
  {
    id: 32,
    name: "error: undefined method `/' for nil:NilClass",
    type: "Sapphire",
    shape: "Emerald",
    weight: 4.7,
    color_grade: "G",
    clarity_grade: "SI2",
    cut_grade: "Excellent",
    price: 6788.9,
    compareAtPrice: 2202.4,
    quantity: 8,
    sku: "magna vestibulum aliquet ultrices erat tortor sollicitudin",
    status: "APPROVED",
    isFeatured: true,
    isActive: true,
    allowOffers: false,
    showOnSaleLabel: false,
    certification: "AGS",
    certificationStatus: false,
    color: "Yellow",
    origin: "ultricies eu nibh quisque id",
    transparency: "Transparent",
    images: [{ url: "https://example.com/images/diamond1.jpg" }],
  },
  {
    id: 33,
    name: "error: undefined method `/' for nil:NilClass",
    type: "Ruby",
    shape: "Princess",
    weight: 4.7,
    color_grade: "G",
    clarity_grade: "I2",
    cut_grade: "Fair",
    price: 9984.5,
    compareAtPrice: 8863.61,
    quantity: 7,
    sku: "luctus tincidunt nulla mollis molestie",
    status: "PENDING",
    isFeatured: true,
    isActive: false,
    allowOffers: false,
    showOnSaleLabel: true,
    certification: "IGI",
    certificationStatus: false,
    color: "Yellow",
    origin: "faucibus orci luctus et ultrices",
    transparency: "Translucent",
    images: [
      { url: "https://example.com/images/diamond1.jpg" },
      { url: "https://example.com/images/diamond1.jpg" },
      { url: "https://example.com/images/diamond1.jpg" },
    ],
  },
  {
    id: 34,
    name: "error: undefined method `/' for nil:NilClass",
    type: "Ruby",
    shape: "Emerald",
    weight: 8.2,
    color_grade: "H",
    clarity_grade: "VVS2",
    cut_grade: "Fair",
    price: 9941.59,
    compareAtPrice: 7704.99,
    quantity: 9,
    sku: "rutrum rutrum neque aenean auctor gravida",
    status: "APPROVED",
    isFeatured: false,
    isActive: true,
    allowOffers: true,
    showOnSaleLabel: true,
    certification: "EGL",
    certificationStatus: true,
    color: "Maroon",
    origin: "nulla sed vel enim sit",
    transparency: "Transparent",
    images: [
      { url: "https://example.com/images/diamond1.jpg" },
      { url: "https://example.com/images/diamond1.jpg" },
    ],
  },
  {
    id: 35,
    name: "error: undefined method `/' for nil:NilClass",
    type: "Emerald",
    shape: "Round",
    weight: 5.7,
    color_grade: "H",
    clarity_grade: "VS1",
    cut_grade: "Fair",
    price: 3805.64,
    compareAtPrice: 1545.45,
    quantity: 9,
    sku: "eros suspendisse accumsan tortor quis turpis",
    status: "PENDING",
    isFeatured: false,
    isActive: false,
    allowOffers: true,
    showOnSaleLabel: false,
    certification: "GIA",
    certificationStatus: false,
    color: "Indigo",
    origin: "amet lobortis sapien sapien non",
    transparency: "Opaque",
    images: [
      { url: "https://example.com/images/diamond1.jpg" },
      { url: "https://example.com/images/diamond1.jpg" },
      { url: "https://example.com/images/diamond1.jpg" },
    ],
  },
  {
    id: 36,
    name: "error: undefined method `/' for nil:NilClass",
    type: "Diamond",
    shape: "Oval",
    weight: 6.1,
    color_grade: "F",
    clarity_grade: "VVS2",
    cut_grade: "Poor",
    price: 8746.04,
    compareAtPrice: 5154.91,
    quantity: 1,
    sku: "nunc donec quis orci eget",
    status: "PENDING",
    isFeatured: true,
    isActive: false,
    allowOffers: false,
    showOnSaleLabel: true,
    certification: "EGL",
    certificationStatus: false,
    color: "Yellow",
    origin: "donec semper sapien a libero",
    transparency: "Opaque",
    images: [{ url: "https://example.com/images/diamond1.jpg" }],
  },
  {
    id: 37,
    name: "error: undefined method `/' for nil:NilClass",
    type: "Ruby",
    shape: "Emerald",
    weight: 1.0,
    color_grade: "I",
    clarity_grade: "I1",
    cut_grade: "Poor",
    price: 6059.34,
    compareAtPrice: 6066.9,
    quantity: 4,
    sku: "morbi odio odio elementum eu",
    status: "PENDING",
    isFeatured: false,
    isActive: true,
    allowOffers: true,
    showOnSaleLabel: false,
    certification: "IGI",
    certificationStatus: false,
    color: "Fuscia",
    origin: "accumsan tellus nisi eu orci",
    transparency: "Transparent",
    images: [
      { url: "https://example.com/images/diamond1.jpg" },
      { url: "https://example.com/images/diamond1.jpg" },
      { url: "https://example.com/images/diamond1.jpg" },
    ],
  },
  {
    id: 38,
    name: "error: undefined method `/' for nil:NilClass",
    type: "Sapphire",
    shape: "Emerald",
    weight: 1.3,
    color_grade: "D",
    clarity_grade: "VVS1",
    cut_grade: "Fair",
    price: 4084.7,
    compareAtPrice: 3909.36,
    quantity: 1,
    sku: "metus arcu adipiscing molestie hendrerit at",
    status: "APPROVED",
    isFeatured: true,
    isActive: true,
    allowOffers: true,
    showOnSaleLabel: false,
    certification: "IGI",
    certificationStatus: true,
    color: "Maroon",
    origin: "curabitur at ipsum ac tellus",
    transparency: "Opaque",
    images: [
      { url: "https://example.com/images/diamond1.jpg" },
      { url: "https://example.com/images/diamond1.jpg" },
    ],
  },
  {
    id: 39,
    name: "error: undefined method `/' for nil:NilClass",
    type: "Diamond",
    shape: "Emerald",
    weight: 3.2,
    color_grade: "J",
    clarity_grade: "SI2",
    cut_grade: "Excellent",
    price: 9349.37,
    compareAtPrice: 7073.0,
    quantity: 8,
    sku: "mi pede malesuada in imperdiet et commodo",
    status: "APPROVED",
    isFeatured: false,
    isActive: false,
    allowOffers: false,
    showOnSaleLabel: false,
    certification: "GIA",
    certificationStatus: true,
    color: "Fuscia",
    origin: "condimentum curabitur in libero ut",
    transparency: "Opaque",
    images: [
      { url: "https://example.com/images/diamond1.jpg" },
      { url: "https://example.com/images/diamond1.jpg" },
    ],
  },
  {
    id: 40,
    name: "error: undefined method `/' for nil:NilClass",
    type: "Emerald",
    shape: "Princess",
    weight: 5.6,
    color_grade: "G",
    clarity_grade: "I3",
    cut_grade: "Poor",
    price: 4189.81,
    compareAtPrice: 5454.61,
    quantity: 2,
    sku: "ridiculus mus etiam vel augue vestibulum",
    status: "PENDING",
    isFeatured: true,
    isActive: true,
    allowOffers: false,
    showOnSaleLabel: false,
    certification: "AGS",
    certificationStatus: false,
    color: "Blue",
    origin: "sit amet diam in magna",
    transparency: "Translucent",
    images: [
      { url: "https://example.com/images/diamond1.jpg" },
      { url: "https://example.com/images/diamond1.jpg" },
      { url: "https://example.com/images/diamond1.jpg" },
    ],
  },
  {
    id: 41,
    name: "error: undefined method `/' for nil:NilClass",
    type: "Diamond",
    shape: "Oval",
    weight: 5.5,
    color_grade: "D",
    clarity_grade: "VS2",
    cut_grade: "Very Good",
    price: 2979.14,
    compareAtPrice: 7163.72,
    quantity: 7,
    sku: "interdum venenatis turpis enim blandit",
    status: "PENDING",
    isFeatured: true,
    isActive: true,
    allowOffers: true,
    showOnSaleLabel: false,
    certification: "GIA",
    certificationStatus: false,
    color: "Pink",
    origin: "rhoncus mauris enim leo rhoncus",
    transparency: "Opaque",
    images: [
      { url: "https://example.com/images/diamond1.jpg" },
      { url: "https://example.com/images/diamond1.jpg" },
      { url: "https://example.com/images/diamond1.jpg" },
    ],
  },
  {
    id: 42,
    name: "error: undefined method `/' for nil:NilClass",
    type: "Diamond",
    shape: "Emerald",
    weight: 3.9,
    color_grade: "F",
    clarity_grade: "I3",
    cut_grade: "Excellent",
    price: 4188.66,
    compareAtPrice: 241.14,
    quantity: 5,
    sku: "consequat varius integer ac leo pellentesque",
    status: "PENDING",
    isFeatured: false,
    isActive: true,
    allowOffers: false,
    showOnSaleLabel: false,
    certification: "AGS",
    certificationStatus: false,
    color: "Violet",
    origin: "suspendisse potenti cras in purus",
    transparency: "Opaque",
    images: [
      { url: "https://example.com/images/diamond1.jpg" },
      { url: "https://example.com/images/diamond1.jpg" },
      { url: "https://example.com/images/diamond1.jpg" },
      { url: "https://example.com/images/diamond1.jpg" },
    ],
  },
  {
    id: 43,
    name: "error: undefined method `/' for nil:NilClass",
    type: "Sapphire",
    shape: "Oval",
    weight: 8.3,
    color_grade: "G",
    clarity_grade: "SI2",
    cut_grade: "Good",
    price: 4069.57,
    compareAtPrice: 6177.79,
    quantity: 7,
    sku: "duis mattis egestas metus aenean",
    status: "APPROVED",
    isFeatured: true,
    isActive: true,
    allowOffers: false,
    showOnSaleLabel: true,
    certification: "AGS",
    certificationStatus: false,
    color: "Turquoise",
    origin: "porta volutpat erat quisque erat",
    transparency: "Opaque",
    images: [
      { url: "https://example.com/images/diamond1.jpg" },
      { url: "https://example.com/images/diamond1.jpg" },
      { url: "https://example.com/images/diamond1.jpg" },
      { url: "https://example.com/images/diamond1.jpg" },
      { url: "https://example.com/images/diamond1.jpg" },
    ],
  },
  {
    id: 44,
    name: "error: undefined method `/' for nil:NilClass",
    type: "Diamond",
    shape: "Emerald",
    weight: 9.2,
    color_grade: "J",
    clarity_grade: "VS2",
    cut_grade: "Poor",
    price: 5877.8,
    compareAtPrice: 4738.63,
    quantity: 0,
    sku: "eu felis fusce posuere felis",
    status: "PENDING",
    isFeatured: false,
    isActive: true,
    allowOffers: true,
    showOnSaleLabel: false,
    certification: "AGS",
    certificationStatus: true,
    color: "Indigo",
    origin: "nulla sed vel enim sit",
    transparency: "Translucent",
    images: [
      { url: "https://example.com/images/diamond1.jpg" },
      { url: "https://example.com/images/diamond1.jpg" },
      { url: "https://example.com/images/diamond1.jpg" },
      { url: "https://example.com/images/diamond1.jpg" },
      { url: "https://example.com/images/diamond1.jpg" },
    ],
  },
  {
    id: 45,
    name: "error: undefined method `/' for nil:NilClass",
    type: "Emerald",
    shape: "Oval",
    weight: 3.3,
    color_grade: "E",
    clarity_grade: "I3",
    cut_grade: "Fair",
    price: 5152.37,
    compareAtPrice: 8236.16,
    quantity: 8,
    sku: "etiam justo etiam pretium iaculis justo in",
    status: "PENDING",
    isFeatured: false,
    isActive: true,
    allowOffers: false,
    showOnSaleLabel: true,
    certification: "IGI",
    certificationStatus: true,
    color: "Pink",
    origin: "justo sit amet sapien dignissim",
    transparency: "Opaque",
    images: [
      { url: "https://example.com/images/diamond1.jpg" },
      { url: "https://example.com/images/diamond1.jpg" },
      { url: "https://example.com/images/diamond1.jpg" },
    ],
  },
  {
    id: 46,
    name: "error: undefined method `/' for nil:NilClass",
    type: "Diamond",
    shape: "Round",
    weight: 2.8,
    color_grade: "F",
    clarity_grade: "VS1",
    cut_grade: "Fair",
    price: 5776.61,
    compareAtPrice: 5541.78,
    quantity: 9,
    sku: "et ultrices posuere cubilia curae mauris",
    status: "PENDING",
    isFeatured: false,
    isActive: false,
    allowOffers: false,
    showOnSaleLabel: true,
    certification: "GIA",
    certificationStatus: true,
    color: "Red",
    origin: "sed ante vivamus tortor duis",
    transparency: "Opaque",
    images: [
      { url: "https://example.com/images/diamond1.jpg" },
      { url: "https://example.com/images/diamond1.jpg" },
      { url: "https://example.com/images/diamond1.jpg" },
      { url: "https://example.com/images/diamond1.jpg" },
    ],
  },
  {
    id: 47,
    name: "error: undefined method `/' for nil:NilClass",
    type: "Sapphire",
    shape: "Princess",
    weight: 7.4,
    color_grade: "H",
    clarity_grade: "I3",
    cut_grade: "Very Good",
    price: 9109.43,
    compareAtPrice: 3994.2,
    quantity: 4,
    sku: "aenean lectus pellentesque eget nunc",
    status: "PENDING",
    isFeatured: true,
    isActive: true,
    allowOffers: false,
    showOnSaleLabel: false,
    certification: "GIA",
    certificationStatus: true,
    color: "Green",
    origin: "pede libero quis orci nullam",
    transparency: "Opaque",
    images: [
      { url: "https://example.com/images/diamond1.jpg" },
      { url: "https://example.com/images/diamond1.jpg" },
      { url: "https://example.com/images/diamond1.jpg" },
    ],
  },
  {
    id: 48,
    name: "error: undefined method `/' for nil:NilClass",
    type: "Diamond",
    shape: "Round",
    weight: 7.2,
    color_grade: "D",
    clarity_grade: "SI2",
    cut_grade: "Excellent",
    price: 6420.84,
    compareAtPrice: 7020.01,
    quantity: 4,
    sku: "maecenas tristique est et tempus",
    status: "PENDING",
    isFeatured: false,
    isActive: false,
    allowOffers: true,
    showOnSaleLabel: false,
    certification: "EGL",
    certificationStatus: false,
    color: "Khaki",
    origin: "odio in hac habitasse platea",
    transparency: "Transparent",
    images: [
      { url: "https://example.com/images/diamond1.jpg" },
      { url: "https://example.com/images/diamond1.jpg" },
      { url: "https://example.com/images/diamond1.jpg" },
    ],
  },
  {
    id: 49,
    name: "error: undefined method `/' for nil:NilClass",
    type: "Emerald",
    shape: "Oval",
    weight: 9.7,
    color_grade: "I",
    clarity_grade: "VS1",
    cut_grade: "Poor",
    price: 4615.39,
    compareAtPrice: 2707.97,
    quantity: 8,
    sku: "rutrum rutrum neque aenean auctor gravida",
    status: "REJECTED",
    isFeatured: false,
    isActive: true,
    allowOffers: true,
    showOnSaleLabel: false,
    certification: "AGS",
    certificationStatus: false,
    color: "Khaki",
    origin: "integer aliquet massa id lobortis",
    transparency: "Opaque",
    images: [
      { url: "https://example.com/images/diamond1.jpg" },
      { url: "https://example.com/images/diamond1.jpg" },
      { url: "https://example.com/images/diamond1.jpg" },
      { url: "https://example.com/images/diamond1.jpg" },
    ],
  },
  {
    id: 50,
    name: "error: undefined method `/' for nil:NilClass",
    type: "Diamond",
    shape: "Oval",
    weight: 0.0,
    color_grade: "I",
    clarity_grade: "SI1",
    cut_grade: "Good",
    price: 1043.06,
    compareAtPrice: 1306.57,
    quantity: 2,
    sku: "etiam vel augue vestibulum rutrum",
    status: "APPROVED",
    isFeatured: true,
    isActive: false,
    allowOffers: false,
    showOnSaleLabel: true,
    certification: "AGS",
    certificationStatus: true,
    color: "Red",
    origin: "libero nullam sit amet turpis",
    transparency: "Translucent",
    images: [{ url: "https://example.com/images/diamond1.jpg" }],
  },
  {
    id: 51,
    name: "error: undefined method `/' for nil:NilClass",
    type: "Diamond",
    shape: "Emerald",
    weight: 8.2,
    color_grade: "D",
    clarity_grade: "SI2",
    cut_grade: "Fair",
    price: 6631.49,
    compareAtPrice: 5329.11,
    quantity: 4,
    sku: "tincidunt ante vel ipsum praesent blandit lacinia",
    status: "PENDING",
    isFeatured: true,
    isActive: false,
    allowOffers: false,
    showOnSaleLabel: false,
    certification: "EGL",
    certificationStatus: true,
    color: "Red",
    origin: "vel sem sed sagittis nam",
    transparency: "Opaque",
    images: [
      { url: "https://example.com/images/diamond1.jpg" },
      { url: "https://example.com/images/diamond1.jpg" },
      { url: "https://example.com/images/diamond1.jpg" },
      { url: "https://example.com/images/diamond1.jpg" },
      { url: "https://example.com/images/diamond1.jpg" },
    ],
  },
  {
    id: 52,
    name: "error: undefined method `/' for nil:NilClass",
    type: "Diamond",
    shape: "Oval",
    weight: 2.1,
    color_grade: "H",
    clarity_grade: "SI1",
    cut_grade: "Fair",
    price: 7286.07,
    compareAtPrice: 2969.73,
    quantity: 9,
    sku: "mauris eget massa tempor convallis nulla",
    status: "PENDING",
    isFeatured: false,
    isActive: true,
    allowOffers: true,
    showOnSaleLabel: true,
    certification: "AGS",
    certificationStatus: false,
    color: "Mauv",
    origin: "accumsan odio curabitur convallis duis",
    transparency: "Opaque",
    images: [
      { url: "https://example.com/images/diamond1.jpg" },
      { url: "https://example.com/images/diamond1.jpg" },
      { url: "https://example.com/images/diamond1.jpg" },
      { url: "https://example.com/images/diamond1.jpg" },
      { url: "https://example.com/images/diamond1.jpg" },
    ],
  },
  {
    id: 53,
    name: "error: undefined method `/' for nil:NilClass",
    type: "Sapphire",
    shape: "Emerald",
    weight: 9.2,
    color_grade: "F",
    clarity_grade: "SI2",
    cut_grade: "Poor",
    price: 6830.93,
    compareAtPrice: 9191.18,
    quantity: 6,
    sku: "eu tincidunt in leo maecenas",
    status: "REJECTED",
    isFeatured: false,
    isActive: false,
    allowOffers: true,
    showOnSaleLabel: false,
    certification: "GIA",
    certificationStatus: true,
    color: "Green",
    origin: "donec ut dolor morbi vel",
    transparency: "Translucent",
    images: [
      { url: "https://example.com/images/diamond1.jpg" },
      { url: "https://example.com/images/diamond1.jpg" },
      { url: "https://example.com/images/diamond1.jpg" },
    ],
  },
  {
    id: 54,
    name: "error: undefined method `/' for nil:NilClass",
    type: "Emerald",
    shape: "Princess",
    weight: 8.3,
    color_grade: "D",
    clarity_grade: "I3",
    cut_grade: "Excellent",
    price: 4686.62,
    compareAtPrice: 8776.8,
    quantity: 10,
    sku: "nulla suscipit ligula in lacus curabitur at",
    status: "APPROVED",
    isFeatured: false,
    isActive: true,
    allowOffers: false,
    showOnSaleLabel: true,
    certification: "GIA",
    certificationStatus: false,
    color: "Crimson",
    origin: "lacinia erat vestibulum sed magna",
    transparency: "Transparent",
    images: [
      { url: "https://example.com/images/diamond1.jpg" },
      { url: "https://example.com/images/diamond1.jpg" },
      { url: "https://example.com/images/diamond1.jpg" },
      { url: "https://example.com/images/diamond1.jpg" },
    ],
  },
  {
    id: 55,
    name: "error: undefined method `/' for nil:NilClass",
    type: "Diamond",
    shape: "Princess",
    weight: 4.3,
    color_grade: "J",
    clarity_grade: "VVS2",
    cut_grade: "Good",
    price: 482.61,
    compareAtPrice: 8962.43,
    quantity: 9,
    sku: "nulla suspendisse potenti cras in",
    status: "REJECTED",
    isFeatured: true,
    isActive: true,
    allowOffers: false,
    showOnSaleLabel: false,
    certification: "GIA",
    certificationStatus: false,
    color: "Red",
    origin: "quam pharetra magna ac consequat",
    transparency: "Translucent",
    images: [
      { url: "https://example.com/images/diamond1.jpg" },
      { url: "https://example.com/images/diamond1.jpg" },
      { url: "https://example.com/images/diamond1.jpg" },
    ],
  },
  {
    id: 56,
    name: "error: undefined method `/' for nil:NilClass",
    type: "Ruby",
    shape: "Oval",
    weight: 0.6,
    color_grade: "H",
    clarity_grade: "VVS2",
    cut_grade: "Fair",
    price: 9087.67,
    compareAtPrice: 1742.35,
    quantity: 6,
    sku: "malesuada in imperdiet et commodo vulputate",
    status: "PENDING",
    isFeatured: false,
    isActive: false,
    allowOffers: false,
    showOnSaleLabel: false,
    certification: "EGL",
    certificationStatus: true,
    color: "Aquamarine",
    origin: "phasellus in felis donec semper",
    transparency: "Translucent",
    images: [
      { url: "https://example.com/images/diamond1.jpg" },
      { url: "https://example.com/images/diamond1.jpg" },
      { url: "https://example.com/images/diamond1.jpg" },
    ],
  },
  {
    id: 57,
    name: "error: undefined method `/' for nil:NilClass",
    type: "Diamond",
    shape: "Princess",
    weight: 8.3,
    color_grade: "D",
    clarity_grade: "SI2",
    cut_grade: "Very Good",
    price: 1741.87,
    compareAtPrice: 7221.09,
    quantity: 7,
    sku: "velit donec diam neque vestibulum eget vulputate",
    status: "PENDING",
    isFeatured: true,
    isActive: true,
    allowOffers: false,
    showOnSaleLabel: true,
    certification: "GIA",
    certificationStatus: false,
    color: "Pink",
    origin: "mus etiam vel augue vestibulum",
    transparency: "Translucent",
    images: [
      { url: "https://example.com/images/diamond1.jpg" },
      { url: "https://example.com/images/diamond1.jpg" },
    ],
  },
  {
    id: 58,
    name: "error: undefined method `/' for nil:NilClass",
    type: "Sapphire",
    shape: "Round",
    weight: 0.1,
    color_grade: "J",
    clarity_grade: "VS1",
    cut_grade: "Poor",
    price: 2235.61,
    compareAtPrice: 213.75,
    quantity: 7,
    sku: "mauris vulputate elementum nullam varius nulla facilisi",
    status: "PENDING",
    isFeatured: false,
    isActive: false,
    allowOffers: false,
    showOnSaleLabel: true,
    certification: "EGL",
    certificationStatus: false,
    color: "Yellow",
    origin: "eget eleifend luctus ultricies eu",
    transparency: "Translucent",
    images: [{ url: "https://example.com/images/diamond1.jpg" }],
  },
  {
    id: 59,
    name: "error: undefined method `/' for nil:NilClass",
    type: "Emerald",
    shape: "Princess",
    weight: 9.0,
    color_grade: "I",
    clarity_grade: "VVS1",
    cut_grade: "Fair",
    price: 3183.16,
    compareAtPrice: 6848.77,
    quantity: 9,
    sku: "justo sollicitudin ut suscipit a",
    status: "APPROVED",
    isFeatured: false,
    isActive: true,
    allowOffers: true,
    showOnSaleLabel: false,
    certification: "GIA",
    certificationStatus: true,
    color: "Aquamarine",
    origin: "tempor convallis nulla neque libero",
    transparency: "Translucent",
    images: [
      { url: "https://example.com/images/diamond1.jpg" },
      { url: "https://example.com/images/diamond1.jpg" },
      { url: "https://example.com/images/diamond1.jpg" },
      { url: "https://example.com/images/diamond1.jpg" },
    ],
  },
  {
    id: 60,
    name: "error: undefined method `/' for nil:NilClass",
    type: "Emerald",
    shape: "Round",
    weight: 6.0,
    color_grade: "I",
    clarity_grade: "I1",
    cut_grade: "Good",
    price: 9072.13,
    compareAtPrice: 3922.1,
    quantity: 3,
    sku: "in leo maecenas pulvinar lobortis est phasellus",
    status: "APPROVED",
    isFeatured: false,
    isActive: false,
    allowOffers: false,
    showOnSaleLabel: true,
    certification: "EGL",
    certificationStatus: false,
    color: "Khaki",
    origin: "eros vestibulum ac est lacinia",
    transparency: "Transparent",
    images: [
      { url: "https://example.com/images/diamond1.jpg" },
      { url: "https://example.com/images/diamond1.jpg" },
    ],
  },
  {
    id: 61,
    name: "error: undefined method `/' for nil:NilClass",
    type: "Ruby",
    shape: "Oval",
    weight: 4.0,
    color_grade: "I",
    clarity_grade: "I2",
    cut_grade: "Good",
    price: 2035.91,
    compareAtPrice: 6868.39,
    quantity: 4,
    sku: "mi integer ac neque duis",
    status: "PENDING",
    isFeatured: false,
    isActive: false,
    allowOffers: true,
    showOnSaleLabel: true,
    certification: "IGI",
    certificationStatus: true,
    color: "Turquoise",
    origin: "potenti nullam porttitor lacus at",
    transparency: "Transparent",
    images: [{ url: "https://example.com/images/diamond1.jpg" }],
  },
  {
    id: 62,
    name: "error: undefined method `/' for nil:NilClass",
    type: "Diamond",
    shape: "Round",
    weight: 1.7,
    color_grade: "H",
    clarity_grade: "I3",
    cut_grade: "Good",
    price: 1359.33,
    compareAtPrice: 2236.51,
    quantity: 5,
    sku: "sollicitudin ut suscipit a feugiat et",
    status: "APPROVED",
    isFeatured: true,
    isActive: true,
    allowOffers: false,
    showOnSaleLabel: true,
    certification: "IGI",
    certificationStatus: false,
    color: "Pink",
    origin: "vestibulum velit id pretium iaculis",
    transparency: "Translucent",
    images: [
      { url: "https://example.com/images/diamond1.jpg" },
      { url: "https://example.com/images/diamond1.jpg" },
      { url: "https://example.com/images/diamond1.jpg" },
      { url: "https://example.com/images/diamond1.jpg" },
    ],
  },
  {
    id: 63,
    name: "error: undefined method `/' for nil:NilClass",
    type: "Diamond",
    shape: "Round",
    weight: 5.7,
    color_grade: "E",
    clarity_grade: "I3",
    cut_grade: "Very Good",
    price: 8150.9,
    compareAtPrice: 9373.29,
    quantity: 4,
    sku: "id mauris vulputate elementum nullam",
    status: "REJECTED",
    isFeatured: false,
    isActive: false,
    allowOffers: false,
    showOnSaleLabel: true,
    certification: "GIA",
    certificationStatus: false,
    color: "Pink",
    origin: "montes nascetur ridiculus mus vivamus",
    transparency: "Opaque",
    images: [
      { url: "https://example.com/images/diamond1.jpg" },
      { url: "https://example.com/images/diamond1.jpg" },
    ],
  },
  {
    id: 64,
    name: "error: undefined method `/' for nil:NilClass",
    type: "Emerald",
    shape: "Princess",
    weight: 7.2,
    color_grade: "I",
    clarity_grade: "I3",
    cut_grade: "Excellent",
    price: 7536.62,
    compareAtPrice: 4687.09,
    quantity: 0,
    sku: "sodales sed tincidunt eu felis",
    status: "REJECTED",
    isFeatured: true,
    isActive: true,
    allowOffers: false,
    showOnSaleLabel: false,
    certification: "AGS",
    certificationStatus: false,
    color: "Red",
    origin: "luctus et ultrices posuere cubilia",
    transparency: "Opaque",
    images: [
      { url: "https://example.com/images/diamond1.jpg" },
      { url: "https://example.com/images/diamond1.jpg" },
      { url: "https://example.com/images/diamond1.jpg" },
    ],
  },
  {
    id: 65,
    name: "error: undefined method `/' for nil:NilClass",
    type: "Emerald",
    shape: "Oval",
    weight: 4.8,
    color_grade: "G",
    clarity_grade: "I1",
    cut_grade: "Very Good",
    price: 8103.43,
    compareAtPrice: 9777.24,
    quantity: 9,
    sku: "vestibulum sed magna at nunc commodo",
    status: "PENDING",
    isFeatured: false,
    isActive: true,
    allowOffers: true,
    showOnSaleLabel: false,
    certification: "EGL",
    certificationStatus: true,
    color: "Maroon",
    origin: "quam turpis adipiscing lorem vitae",
    transparency: "Transparent",
    images: [
      { url: "https://example.com/images/diamond1.jpg" },
      { url: "https://example.com/images/diamond1.jpg" },
      { url: "https://example.com/images/diamond1.jpg" },
    ],
  },
  {
    id: 66,
    name: "error: undefined method `/' for nil:NilClass",
    type: "Emerald",
    shape: "Princess",
    weight: 5.7,
    color_grade: "E",
    clarity_grade: "I2",
    cut_grade: "Fair",
    price: 1591.23,
    compareAtPrice: 1537.89,
    quantity: 0,
    sku: "nulla dapibus dolor vel est",
    status: "REJECTED",
    isFeatured: true,
    isActive: false,
    allowOffers: true,
    showOnSaleLabel: false,
    certification: "AGS",
    certificationStatus: false,
    color: "Red",
    origin: "turpis elementum ligula vehicula consequat",
    transparency: "Transparent",
    images: [
      { url: "https://example.com/images/diamond1.jpg" },
      { url: "https://example.com/images/diamond1.jpg" },
      { url: "https://example.com/images/diamond1.jpg" },
    ],
  },
  {
    id: 67,
    name: "error: undefined method `/' for nil:NilClass",
    type: "Sapphire",
    shape: "Princess",
    weight: 1.3,
    color_grade: "J",
    clarity_grade: "I3",
    cut_grade: "Fair",
    price: 8669.34,
    compareAtPrice: 1011.46,
    quantity: 7,
    sku: "orci eget orci vehicula condimentum curabitur",
    status: "APPROVED",
    isFeatured: false,
    isActive: false,
    allowOffers: true,
    showOnSaleLabel: false,
    certification: "GIA",
    certificationStatus: true,
    color: "Yellow",
    origin: "nec condimentum neque sapien placerat",
    transparency: "Opaque",
    images: [{ url: "https://example.com/images/diamond1.jpg" }],
  },
  {
    id: 68,
    name: "error: undefined method `/' for nil:NilClass",
    type: "Ruby",
    shape: "Princess",
    weight: 3.4,
    color_grade: "I",
    clarity_grade: "VS2",
    cut_grade: "Excellent",
    price: 9666.65,
    compareAtPrice: 698.18,
    quantity: 10,
    sku: "mi sit amet lobortis sapien sapien non",
    status: "APPROVED",
    isFeatured: false,
    isActive: false,
    allowOffers: true,
    showOnSaleLabel: false,
    certification: "GIA",
    certificationStatus: false,
    color: "Violet",
    origin: "proin eu mi nulla ac",
    transparency: "Opaque",
    images: [
      { url: "https://example.com/images/diamond1.jpg" },
      { url: "https://example.com/images/diamond1.jpg" },
      { url: "https://example.com/images/diamond1.jpg" },
      { url: "https://example.com/images/diamond1.jpg" },
      { url: "https://example.com/images/diamond1.jpg" },
    ],
  },
  {
    id: 69,
    name: "error: undefined method `/' for nil:NilClass",
    type: "Diamond",
    shape: "Princess",
    weight: 7.6,
    color_grade: "F",
    clarity_grade: "VVS1",
    cut_grade: "Poor",
    price: 8928.53,
    compareAtPrice: 5858.38,
    quantity: 5,
    sku: "rutrum nulla tellus in sagittis dui vel",
    status: "REJECTED",
    isFeatured: true,
    isActive: false,
    allowOffers: false,
    showOnSaleLabel: false,
    certification: "GIA",
    certificationStatus: false,
    color: "Blue",
    origin: "mus vivamus vestibulum sagittis sapien",
    transparency: "Transparent",
    images: [
      { url: "https://example.com/images/diamond1.jpg" },
      { url: "https://example.com/images/diamond1.jpg" },
    ],
  },
  {
    id: 70,
    name: "error: undefined method `/' for nil:NilClass",
    type: "Ruby",
    shape: "Emerald",
    weight: 0.4,
    color_grade: "I",
    clarity_grade: "SI1",
    cut_grade: "Poor",
    price: 2148.34,
    compareAtPrice: 4821.78,
    quantity: 6,
    sku: "id mauris vulputate elementum nullam varius nulla",
    status: "REJECTED",
    isFeatured: false,
    isActive: true,
    allowOffers: false,
    showOnSaleLabel: false,
    certification: "IGI",
    certificationStatus: true,
    color: "Mauv",
    origin: "dapibus duis at velit eu",
    transparency: "Opaque",
    images: [
      { url: "https://example.com/images/diamond1.jpg" },
      { url: "https://example.com/images/diamond1.jpg" },
      { url: "https://example.com/images/diamond1.jpg" },
      { url: "https://example.com/images/diamond1.jpg" },
    ],
  },
  {
    id: 71,
    name: "error: undefined method `/' for nil:NilClass",
    type: "Emerald",
    shape: "Emerald",
    weight: 8.8,
    color_grade: "D",
    clarity_grade: "VVS1",
    cut_grade: "Excellent",
    price: 778.46,
    compareAtPrice: 7637.48,
    quantity: 5,
    sku: "praesent blandit nam nulla integer pede",
    status: "REJECTED",
    isFeatured: true,
    isActive: false,
    allowOffers: true,
    showOnSaleLabel: true,
    certification: "IGI",
    certificationStatus: false,
    color: "Maroon",
    origin: "vestibulum ante ipsum primis in",
    transparency: "Opaque",
    images: [
      { url: "https://example.com/images/diamond1.jpg" },
      { url: "https://example.com/images/diamond1.jpg" },
      { url: "https://example.com/images/diamond1.jpg" },
      { url: "https://example.com/images/diamond1.jpg" },
      { url: "https://example.com/images/diamond1.jpg" },
    ],
  },
  {
    id: 72,
    name: "error: undefined method `/' for nil:NilClass",
    type: "Sapphire",
    shape: "Princess",
    weight: 8.8,
    color_grade: "E",
    clarity_grade: "SI1",
    cut_grade: "Fair",
    price: 6219.49,
    compareAtPrice: 4035.87,
    quantity: 2,
    sku: "hac habitasse platea dictumst morbi vestibulum velit",
    status: "REJECTED",
    isFeatured: false,
    isActive: true,
    allowOffers: false,
    showOnSaleLabel: true,
    certification: "EGL",
    certificationStatus: false,
    color: "Crimson",
    origin: "id nisl venenatis lacinia aenean",
    transparency: "Translucent",
    images: [
      { url: "https://example.com/images/diamond1.jpg" },
      { url: "https://example.com/images/diamond1.jpg" },
      { url: "https://example.com/images/diamond1.jpg" },
      { url: "https://example.com/images/diamond1.jpg" },
      { url: "https://example.com/images/diamond1.jpg" },
    ],
  },
  {
    id: 73,
    name: "error: undefined method `/' for nil:NilClass",
    type: "Sapphire",
    shape: "Emerald",
    weight: 1.9,
    color_grade: "J",
    clarity_grade: "VS2",
    cut_grade: "Excellent",
    price: 6719.35,
    compareAtPrice: 9333.79,
    quantity: 10,
    sku: "amet cursus id turpis integer aliquet massa",
    status: "REJECTED",
    isFeatured: true,
    isActive: true,
    allowOffers: false,
    showOnSaleLabel: false,
    certification: "IGI",
    certificationStatus: false,
    color: "Puce",
    origin: "turpis adipiscing lorem vitae mattis",
    transparency: "Opaque",
    images: [
      { url: "https://example.com/images/diamond1.jpg" },
      { url: "https://example.com/images/diamond1.jpg" },
      { url: "https://example.com/images/diamond1.jpg" },
    ],
  },
  {
    id: 74,
    name: "error: undefined method `/' for nil:NilClass",
    type: "Diamond",
    shape: "Princess",
    weight: 4.1,
    color_grade: "H",
    clarity_grade: "VS1",
    cut_grade: "Very Good",
    price: 5288.85,
    compareAtPrice: 5815.86,
    quantity: 7,
    sku: "ipsum primis in faucibus orci",
    status: "PENDING",
    isFeatured: true,
    isActive: false,
    allowOffers: true,
    showOnSaleLabel: true,
    certification: "EGL",
    certificationStatus: false,
    color: "Khaki",
    origin: "vulputate vitae nisl aenean lectus",
    transparency: "Opaque",
    images: [
      { url: "https://example.com/images/diamond1.jpg" },
      { url: "https://example.com/images/diamond1.jpg" },
      { url: "https://example.com/images/diamond1.jpg" },
    ],
  },
  {
    id: 75,
    name: "error: undefined method `/' for nil:NilClass",
    type: "Ruby",
    shape: "Emerald",
    weight: 4.0,
    color_grade: "D",
    clarity_grade: "I3",
    cut_grade: "Excellent",
    price: 2092.12,
    compareAtPrice: 7732.95,
    quantity: 10,
    sku: "integer ac leo pellentesque ultrices",
    status: "PENDING",
    isFeatured: true,
    isActive: false,
    allowOffers: false,
    showOnSaleLabel: false,
    certification: "IGI",
    certificationStatus: true,
    color: "Khaki",
    origin: "lobortis est phasellus sit amet",
    transparency: "Opaque",
    images: [
      { url: "https://example.com/images/diamond1.jpg" },
      { url: "https://example.com/images/diamond1.jpg" },
      { url: "https://example.com/images/diamond1.jpg" },
      { url: "https://example.com/images/diamond1.jpg" },
      { url: "https://example.com/images/diamond1.jpg" },
    ],
  },
  {
    id: 76,
    name: "error: undefined method `/' for nil:NilClass",
    type: "Ruby",
    shape: "Emerald",
    weight: 0.9,
    color_grade: "E",
    clarity_grade: "I2",
    cut_grade: "Poor",
    price: 2541.53,
    compareAtPrice: 2589.25,
    quantity: 10,
    sku: "odio porttitor id consequat in consequat ut",
    status: "APPROVED",
    isFeatured: true,
    isActive: false,
    allowOffers: false,
    showOnSaleLabel: false,
    certification: "IGI",
    certificationStatus: false,
    color: "Yellow",
    origin: "sed nisl nunc rhoncus dui",
    transparency: "Translucent",
    images: [
      { url: "https://example.com/images/diamond1.jpg" },
      { url: "https://example.com/images/diamond1.jpg" },
      { url: "https://example.com/images/diamond1.jpg" },
      { url: "https://example.com/images/diamond1.jpg" },
    ],
  },
  {
    id: 77,
    name: "error: undefined method `/' for nil:NilClass",
    type: "Emerald",
    shape: "Emerald",
    weight: 4.7,
    color_grade: "E",
    clarity_grade: "VS2",
    cut_grade: "Fair",
    price: 5523.64,
    compareAtPrice: 7835.0,
    quantity: 0,
    sku: "praesent id massa id nisl venenatis lacinia",
    status: "PENDING",
    isFeatured: true,
    isActive: false,
    allowOffers: false,
    showOnSaleLabel: false,
    certification: "AGS",
    certificationStatus: true,
    color: "Puce",
    origin: "id massa id nisl venenatis",
    transparency: "Opaque",
    images: [
      { url: "https://example.com/images/diamond1.jpg" },
      { url: "https://example.com/images/diamond1.jpg" },
      { url: "https://example.com/images/diamond1.jpg" },
    ],
  },
  {
    id: 78,
    name: "error: undefined method `/' for nil:NilClass",
    type: "Diamond",
    shape: "Round",
    weight: 7.7,
    color_grade: "E",
    clarity_grade: "I3",
    cut_grade: "Excellent",
    price: 171.9,
    compareAtPrice: 4033.36,
    quantity: 10,
    sku: "mauris enim leo rhoncus sed vestibulum",
    status: "PENDING",
    isFeatured: false,
    isActive: true,
    allowOffers: false,
    showOnSaleLabel: true,
    certification: "EGL",
    certificationStatus: true,
    color: "Violet",
    origin: "lacus at turpis donec posuere",
    transparency: "Transparent",
    images: [
      { url: "https://example.com/images/diamond1.jpg" },
      { url: "https://example.com/images/diamond1.jpg" },
      { url: "https://example.com/images/diamond1.jpg" },
      { url: "https://example.com/images/diamond1.jpg" },
    ],
  },
  {
    id: 79,
    name: "error: undefined method `/' for nil:NilClass",
    type: "Sapphire",
    shape: "Oval",
    weight: 0.6,
    color_grade: "J",
    clarity_grade: "I1",
    cut_grade: "Excellent",
    price: 8440.9,
    compareAtPrice: 7446.98,
    quantity: 6,
    sku: "luctus et ultrices posuere cubilia curae",
    status: "PENDING",
    isFeatured: true,
    isActive: false,
    allowOffers: true,
    showOnSaleLabel: false,
    certification: "AGS",
    certificationStatus: true,
    color: "Teal",
    origin: "faucibus orci luctus et ultrices",
    transparency: "Transparent",
    images: [{ url: "https://example.com/images/diamond1.jpg" }],
  },
  {
    id: 80,
    name: "error: undefined method `/' for nil:NilClass",
    type: "Diamond",
    shape: "Emerald",
    weight: 2.4,
    color_grade: "G",
    clarity_grade: "VVS2",
    cut_grade: "Fair",
    price: 144.15,
    compareAtPrice: 2682.32,
    quantity: 6,
    sku: "amet eros suspendisse accumsan tortor",
    status: "PENDING",
    isFeatured: false,
    isActive: true,
    allowOffers: true,
    showOnSaleLabel: false,
    certification: "GIA",
    certificationStatus: false,
    color: "Maroon",
    origin: "ornare consequat lectus in est",
    transparency: "Opaque",
    images: [
      { url: "https://example.com/images/diamond1.jpg" },
      { url: "https://example.com/images/diamond1.jpg" },
      { url: "https://example.com/images/diamond1.jpg" },
      { url: "https://example.com/images/diamond1.jpg" },
      { url: "https://example.com/images/diamond1.jpg" },
    ],
  },
  {
    id: 81,
    name: "error: undefined method `/' for nil:NilClass",
    type: "Emerald",
    shape: "Oval",
    weight: 5.7,
    color_grade: "H",
    clarity_grade: "VS1",
    cut_grade: "Very Good",
    price: 4472.19,
    compareAtPrice: 7892.99,
    quantity: 6,
    sku: "feugiat et eros vestibulum ac",
    status: "APPROVED",
    isFeatured: false,
    isActive: true,
    allowOffers: false,
    showOnSaleLabel: false,
    certification: "EGL",
    certificationStatus: false,
    color: "Crimson",
    origin: "neque sapien placerat ante nulla",
    transparency: "Translucent",
    images: [{ url: "https://example.com/images/diamond1.jpg" }],
  },
  {
    id: 82,
    name: "error: undefined method `/' for nil:NilClass",
    type: "Ruby",
    shape: "Round",
    weight: 8.1,
    color_grade: "E",
    clarity_grade: "VVS1",
    cut_grade: "Good",
    price: 2326.41,
    compareAtPrice: 792.45,
    quantity: 10,
    sku: "id lobortis convallis tortor risus dapibus augue",
    status: "APPROVED",
    isFeatured: true,
    isActive: false,
    allowOffers: false,
    showOnSaleLabel: false,
    certification: "EGL",
    certificationStatus: true,
    color: "Fuscia",
    origin: "ut erat curabitur gravida nisi",
    transparency: "Opaque",
    images: [
      { url: "https://example.com/images/diamond1.jpg" },
      { url: "https://example.com/images/diamond1.jpg" },
      { url: "https://example.com/images/diamond1.jpg" },
      { url: "https://example.com/images/diamond1.jpg" },
      { url: "https://example.com/images/diamond1.jpg" },
    ],
  },
  {
    id: 83,
    name: "error: undefined method `/' for nil:NilClass",
    type: "Emerald",
    shape: "Oval",
    weight: 2.3,
    color_grade: "I",
    clarity_grade: "VVS1",
    cut_grade: "Very Good",
    price: 9257.34,
    compareAtPrice: 9811.52,
    quantity: 1,
    sku: "eget vulputate ut ultrices vel augue",
    status: "REJECTED",
    isFeatured: true,
    isActive: false,
    allowOffers: false,
    showOnSaleLabel: false,
    certification: "IGI",
    certificationStatus: false,
    color: "Indigo",
    origin: "ut erat curabitur gravida nisi",
    transparency: "Opaque",
    images: [
      { url: "https://example.com/images/diamond1.jpg" },
      { url: "https://example.com/images/diamond1.jpg" },
      { url: "https://example.com/images/diamond1.jpg" },
      { url: "https://example.com/images/diamond1.jpg" },
    ],
  },
  {
    id: 84,
    name: "error: undefined method `/' for nil:NilClass",
    type: "Diamond",
    shape: "Princess",
    weight: 3.3,
    color_grade: "E",
    clarity_grade: "I3",
    cut_grade: "Excellent",
    price: 4332.53,
    compareAtPrice: 5074.09,
    quantity: 10,
    sku: "ante ipsum primis in faucibus orci",
    status: "APPROVED",
    isFeatured: false,
    isActive: false,
    allowOffers: true,
    showOnSaleLabel: true,
    certification: "GIA",
    certificationStatus: true,
    color: "Violet",
    origin: "nec sem duis aliquam convallis",
    transparency: "Opaque",
    images: [
      { url: "https://example.com/images/diamond1.jpg" },
      { url: "https://example.com/images/diamond1.jpg" },
      { url: "https://example.com/images/diamond1.jpg" },
    ],
  },
  {
    id: 85,
    name: "error: undefined method `/' for nil:NilClass",
    type: "Emerald",
    shape: "Emerald",
    weight: 5.5,
    color_grade: "F",
    clarity_grade: "VS2",
    cut_grade: "Fair",
    price: 7358.87,
    compareAtPrice: 8407.98,
    quantity: 9,
    sku: "congue vivamus metus arcu adipiscing molestie",
    status: "REJECTED",
    isFeatured: false,
    isActive: false,
    allowOffers: true,
    showOnSaleLabel: true,
    certification: "AGS",
    certificationStatus: false,
    color: "Violet",
    origin: "tincidunt eget tempus vel pede",
    transparency: "Opaque",
    images: [
      { url: "https://example.com/images/diamond1.jpg" },
      { url: "https://example.com/images/diamond1.jpg" },
      { url: "https://example.com/images/diamond1.jpg" },
      { url: "https://example.com/images/diamond1.jpg" },
      { url: "https://example.com/images/diamond1.jpg" },
    ],
  },
  {
    id: 86,
    name: "error: undefined method `/' for nil:NilClass",
    type: "Ruby",
    shape: "Emerald",
    weight: 5.7,
    color_grade: "G",
    clarity_grade: "VVS1",
    cut_grade: "Very Good",
    price: 4528.14,
    compareAtPrice: 9239.13,
    quantity: 6,
    sku: "justo sit amet sapien dignissim vestibulum vestibulum",
    status: "REJECTED",
    isFeatured: true,
    isActive: true,
    allowOffers: true,
    showOnSaleLabel: true,
    certification: "AGS",
    certificationStatus: true,
    color: "Crimson",
    origin: "sit amet consectetuer adipiscing elit",
    transparency: "Transparent",
    images: [
      { url: "https://example.com/images/diamond1.jpg" },
      { url: "https://example.com/images/diamond1.jpg" },
      { url: "https://example.com/images/diamond1.jpg" },
    ],
  },
  {
    id: 87,
    name: "error: undefined method `/' for nil:NilClass",
    type: "Ruby",
    shape: "Princess",
    weight: 1.6,
    color_grade: "I",
    clarity_grade: "SI2",
    cut_grade: "Good",
    price: 880.3,
    compareAtPrice: 359.45,
    quantity: 7,
    sku: "a pede posuere nonummy integer",
    status: "APPROVED",
    isFeatured: true,
    isActive: false,
    allowOffers: false,
    showOnSaleLabel: true,
    certification: "IGI",
    certificationStatus: false,
    color: "Yellow",
    origin: "non interdum in ante vestibulum",
    transparency: "Translucent",
    images: [
      { url: "https://example.com/images/diamond1.jpg" },
      { url: "https://example.com/images/diamond1.jpg" },
      { url: "https://example.com/images/diamond1.jpg" },
      { url: "https://example.com/images/diamond1.jpg" },
      { url: "https://example.com/images/diamond1.jpg" },
    ],
  },
  {
    id: 88,
    name: "error: undefined method `/' for nil:NilClass",
    type: "Sapphire",
    shape: "Emerald",
    weight: 4.3,
    color_grade: "F",
    clarity_grade: "VS1",
    cut_grade: "Fair",
    price: 5135.33,
    compareAtPrice: 1168.3,
    quantity: 8,
    sku: "lectus vestibulum quam sapien varius",
    status: "APPROVED",
    isFeatured: true,
    isActive: false,
    allowOffers: true,
    showOnSaleLabel: false,
    certification: "AGS",
    certificationStatus: true,
    color: "Blue",
    origin: "congue eget semper rutrum nulla",
    transparency: "Opaque",
    images: [
      { url: "https://example.com/images/diamond1.jpg" },
      { url: "https://example.com/images/diamond1.jpg" },
      { url: "https://example.com/images/diamond1.jpg" },
    ],
  },
  {
    id: 89,
    name: "error: undefined method `/' for nil:NilClass",
    type: "Sapphire",
    shape: "Princess",
    weight: 5.6,
    color_grade: "J",
    clarity_grade: "VS2",
    cut_grade: "Excellent",
    price: 4169.21,
    compareAtPrice: 5099.43,
    quantity: 4,
    sku: "risus semper porta volutpat quam pede",
    status: "PENDING",
    isFeatured: true,
    isActive: true,
    allowOffers: false,
    showOnSaleLabel: false,
    certification: "AGS",
    certificationStatus: true,
    color: "Orange",
    origin: "dis parturient montes nascetur ridiculus",
    transparency: "Opaque",
    images: [
      { url: "https://example.com/images/diamond1.jpg" },
      { url: "https://example.com/images/diamond1.jpg" },
    ],
  },
  {
    id: 90,
    name: "error: undefined method `/' for nil:NilClass",
    type: "Diamond",
    shape: "Princess",
    weight: 1.6,
    color_grade: "G",
    clarity_grade: "SI1",
    cut_grade: "Very Good",
    price: 3787.88,
    compareAtPrice: 2014.46,
    quantity: 7,
    sku: "blandit ultrices enim lorem ipsum dolor",
    status: "APPROVED",
    isFeatured: false,
    isActive: true,
    allowOffers: false,
    showOnSaleLabel: false,
    certification: "AGS",
    certificationStatus: true,
    color: "Turquoise",
    origin: "vulputate luctus cum sociis natoque",
    transparency: "Translucent",
    images: [
      { url: "https://example.com/images/diamond1.jpg" },
      { url: "https://example.com/images/diamond1.jpg" },
    ],
  },
  {
    id: 91,
    name: "error: undefined method `/' for nil:NilClass",
    type: "Diamond",
    shape: "Round",
    weight: 2.0,
    color_grade: "H",
    clarity_grade: "SI1",
    cut_grade: "Excellent",
    price: 6388.12,
    compareAtPrice: 9527.06,
    quantity: 10,
    sku: "tincidunt ante vel ipsum praesent",
    status: "APPROVED",
    isFeatured: true,
    isActive: true,
    allowOffers: true,
    showOnSaleLabel: false,
    certification: "AGS",
    certificationStatus: false,
    color: "Fuscia",
    origin: "nisl ut volutpat sapien arcu",
    transparency: "Opaque",
    images: [
      { url: "https://example.com/images/diamond1.jpg" },
      { url: "https://example.com/images/diamond1.jpg" },
      { url: "https://example.com/images/diamond1.jpg" },
    ],
  },
  {
    id: 92,
    name: "error: undefined method `/' for nil:NilClass",
    type: "Sapphire",
    shape: "Princess",
    weight: 2.0,
    color_grade: "E",
    clarity_grade: "I1",
    cut_grade: "Poor",
    price: 7247.67,
    compareAtPrice: 544.16,
    quantity: 6,
    sku: "in felis eu sapien cursus vestibulum",
    status: "REJECTED",
    isFeatured: true,
    isActive: true,
    allowOffers: true,
    showOnSaleLabel: false,
    certification: "AGS",
    certificationStatus: true,
    color: "Puce",
    origin: "cursus urna ut tellus nulla",
    transparency: "Opaque",
    images: [
      { url: "https://example.com/images/diamond1.jpg" },
      { url: "https://example.com/images/diamond1.jpg" },
      { url: "https://example.com/images/diamond1.jpg" },
    ],
  },
  {
    id: 93,
    name: "error: undefined method `/' for nil:NilClass",
    type: "Diamond",
    shape: "Emerald",
    weight: 1.6,
    color_grade: "G",
    clarity_grade: "VVS1",
    cut_grade: "Excellent",
    price: 4055.03,
    compareAtPrice: 2820.03,
    quantity: 10,
    sku: "praesent blandit nam nulla integer pede justo",
    status: "PENDING",
    isFeatured: false,
    isActive: false,
    allowOffers: true,
    showOnSaleLabel: true,
    certification: "AGS",
    certificationStatus: false,
    color: "Khaki",
    origin: "integer ac leo pellentesque ultrices",
    transparency: "Transparent",
    images: [
      { url: "https://example.com/images/diamond1.jpg" },
      { url: "https://example.com/images/diamond1.jpg" },
      { url: "https://example.com/images/diamond1.jpg" },
      { url: "https://example.com/images/diamond1.jpg" },
    ],
  },
  {
    id: 94,
    name: "error: undefined method `/' for nil:NilClass",
    type: "Ruby",
    shape: "Round",
    weight: 1.1,
    color_grade: "I",
    clarity_grade: "VVS1",
    cut_grade: "Excellent",
    price: 8958.77,
    compareAtPrice: 7864.29,
    quantity: 6,
    sku: "mus vivamus vestibulum sagittis sapien cum sociis",
    status: "REJECTED",
    isFeatured: true,
    isActive: true,
    allowOffers: true,
    showOnSaleLabel: true,
    certification: "EGL",
    certificationStatus: false,
    color: "Crimson",
    origin: "vel nulla eget eros elementum",
    transparency: "Transparent",
    images: [
      { url: "https://example.com/images/diamond1.jpg" },
      { url: "https://example.com/images/diamond1.jpg" },
    ],
  },
  {
    id: 95,
    name: "error: undefined method `/' for nil:NilClass",
    type: "Emerald",
    shape: "Princess",
    weight: 8.3,
    color_grade: "F",
    clarity_grade: "I3",
    cut_grade: "Poor",
    price: 7967.1,
    compareAtPrice: 8431.0,
    quantity: 7,
    sku: "facilisi cras non velit nec nisi vulputate",
    status: "PENDING",
    isFeatured: false,
    isActive: false,
    allowOffers: false,
    showOnSaleLabel: true,
    certification: "EGL",
    certificationStatus: true,
    color: "Blue",
    origin: "praesent blandit nam nulla integer",
    transparency: "Transparent",
    images: [
      { url: "https://example.com/images/diamond1.jpg" },
      { url: "https://example.com/images/diamond1.jpg" },
      { url: "https://example.com/images/diamond1.jpg" },
      { url: "https://example.com/images/diamond1.jpg" },
      { url: "https://example.com/images/diamond1.jpg" },
    ],
  },
  {
    id: 96,
    name: "error: undefined method `/' for nil:NilClass",
    type: "Diamond",
    shape: "Round",
    weight: 5.5,
    color_grade: "J",
    clarity_grade: "VS1",
    cut_grade: "Poor",
    price: 8987.96,
    compareAtPrice: 9096.59,
    quantity: 10,
    sku: "nunc nisl duis bibendum felis sed",
    status: "APPROVED",
    isFeatured: true,
    isActive: true,
    allowOffers: false,
    showOnSaleLabel: true,
    certification: "GIA",
    certificationStatus: false,
    color: "Maroon",
    origin: "ultrices posuere cubilia curae duis",
    transparency: "Opaque",
    images: [
      { url: "https://example.com/images/diamond1.jpg" },
      { url: "https://example.com/images/diamond1.jpg" },
      { url: "https://example.com/images/diamond1.jpg" },
      { url: "https://example.com/images/diamond1.jpg" },
    ],
  },
  {
    id: 97,
    name: "error: undefined method `/' for nil:NilClass",
    type: "Emerald",
    shape: "Emerald",
    weight: 5.2,
    color_grade: "D",
    clarity_grade: "VVS1",
    cut_grade: "Fair",
    price: 8343.78,
    compareAtPrice: 5273.38,
    quantity: 9,
    sku: "metus aenean fermentum donec ut mauris eget",
    status: "APPROVED",
    isFeatured: false,
    isActive: true,
    allowOffers: false,
    showOnSaleLabel: true,
    certification: "EGL",
    certificationStatus: false,
    color: "Indigo",
    origin: "fusce lacus purus aliquet at",
    transparency: "Opaque",
    images: [{ url: "https://example.com/images/diamond1.jpg" }],
  },
  {
    id: 98,
    name: "error: undefined method `/' for nil:NilClass",
    type: "Sapphire",
    shape: "Emerald",
    weight: 1.1,
    color_grade: "F",
    clarity_grade: "SI2",
    cut_grade: "Very Good",
    price: 3534.92,
    compareAtPrice: 6327.61,
    quantity: 3,
    sku: "donec dapibus duis at velit eu",
    status: "PENDING",
    isFeatured: false,
    isActive: true,
    allowOffers: true,
    showOnSaleLabel: true,
    certification: "IGI",
    certificationStatus: true,
    color: "Green",
    origin: "ac leo pellentesque ultrices mattis",
    transparency: "Opaque",
    images: [{ url: "https://example.com/images/diamond1.jpg" }],
  },
  {
    id: 99,
    name: "error: undefined method `/' for nil:NilClass",
    type: "Diamond",
    shape: "Princess",
    weight: 6.9,
    color_grade: "H",
    clarity_grade: "SI2",
    cut_grade: "Good",
    price: 4755.69,
    compareAtPrice: 6409.97,
    quantity: 2,
    sku: "consectetuer adipiscing elit proin interdum mauris",
    status: "APPROVED",
    isFeatured: true,
    isActive: false,
    allowOffers: true,
    showOnSaleLabel: false,
    certification: "EGL",
    certificationStatus: false,
    color: "Khaki",
    origin: "ante vel ipsum praesent blandit",
    transparency: "Transparent",
    images: [
      { url: "https://example.com/images/diamond1.jpg" },
      { url: "https://example.com/images/diamond1.jpg" },
      { url: "https://example.com/images/diamond1.jpg" },
      { url: "https://example.com/images/diamond1.jpg" },
    ],
  },
  {
    id: 100,
    name: "error: undefined method `/' for nil:NilClass",
    type: "Ruby",
    shape: "Round",
    weight: 8.8,
    color_grade: "J",
    clarity_grade: "VVS1",
    cut_grade: "Poor",
    price: 3747.15,
    compareAtPrice: 2865.57,
    quantity: 8,
    sku: "nisi at nibh in hac",
    status: "APPROVED",
    isFeatured: true,
    isActive: true,
    allowOffers: false,
    showOnSaleLabel: true,
    certification: "EGL",
    certificationStatus: false,
    color: "Red",
    origin: "accumsan tortor quis turpis sed",
    transparency: "Opaque",
    images: [{ url: "https://example.com/images/diamond1.jpg" }],
  },
];
const GemstonePage = () => {
  const [open, setOpen] = React.useState<boolean>(false);
  const [rows, setRows] = React.useState<any[]>(endoserdata);

  //   const { detailCards } = useSelector((state) => state.user);
  const [rowValue, setRowValue] = React.useState(null);

  //   React.useEffect(() => {
  //     setUsers(detailCards);
  //   }, [detailCards]);

  React.useEffect(() => {
    if (!rowValue) return;
    const { id } = rowValue;
    window.location.href = `/dashboard/gemstone/details/${encodeURIComponent(id)}`;
  }, [rowValue]);

  return (
    <MainCard content={false}>
      {/* filter section */}
      <CardContent>
        <EndoserTableFilter {...{ rows, setRows }} />
      </CardContent>

      {/* table */}
      <Box display={open ? "flex" : "block"}>
        <Grid container sx={{ position: "relative" }}>
          <Grid size={{ sm: open ? 5 : 12, xs: 12 }}>
            <TableProvider>
              <GenericTable
                open={open}
                setOpen={setOpen}
                data={rows}
                setRowValue={setRowValue}
                HeaderComponent={GemstoneTableHeader}
                BodyComponent={GemstoneTableRows}
              />
            </TableProvider>
          </Grid>
        </Grid>
      </Box>
    </MainCard>
  );
};

export default GemstonePage;
