"use client";

import * as React from "react";

// material-ui
import Box from "@mui/material/Box";
import CardContent from "@mui/material/CardContent";
import Grid from "@mui/material/Grid";

// project-imports

import { dispatch, useSelector } from "store";
import { getDetailCards } from "store/slices/user";

// types
import { UserProfile } from "types/user-profile";
import MainCard from "@/components/cards/MainCard";
import CustomTable from "@/components/table/Table";
import CustomDrawer from "@/components/drawer/Drawer";
import UserDetails from "@/components/users/UserDetails";
import UserFilter from "@/components/users/UserFilter";
import { TableProvider } from "@/contexts/TableContext";
import GenericTable from "@/components/table/GenericTable";
import EndoserTableHeader from "@/components/endoser/table/EndoserTableHeader";
import EndoserTableFilter from "@/components/endoser/table/EndoserTableFilter";
import EndoserTableRows from "@/components/endoser/table/EndoserTableRows";
import EndoserDetails from "@/components/endoser/EndoserDetails";

const endoserdata = [
  {
    id: 1,
    firstName: "Brade",
    lastName: "Brafield",
    email: "bbrafield0@chron.com",
    phoneNumber: "632-709-1808",
    certificationType: "Graduate Gemologist",
    certifyingAuthority: "AGS",
    yearsOfExperience: 26,
    specialization: ["Diamonds"],
    status: "Inactive",
    lastVerifiedDate: "4/22/2025",
  },
  {
    id: 2,
    firstName: "Val",
    lastName: "Tampling",
    email: "vtampling1@shutterfly.com",
    phoneNumber: "949-366-5750",
    certificationType: "Certified Appraiser",
    certifyingAuthority: "IGI",
    yearsOfExperience: 12,
    specialization: ["Sapphires"],
    status: "Active",
    lastVerifiedDate: "4/22/2025",
  },
  {
    id: 3,
    firstName: "Celesta",
    lastName: "Ayrs",
    email: "cayrs2@squidoo.com",
    phoneNumber: "387-178-6010",
    certificationType: "Graduate Gemologist",
    certifyingAuthority: "GIA",
    yearsOfExperience: 39,
    specialization: ["Rubies", "Diamonds"],
    status: "Pending Verification",
    lastVerifiedDate: "4/22/2025",
  },
  {
    id: 4,
    firstName: "Anne",
    lastName: "Noen",
    email: "anoen3@webs.com",
    phoneNumber: "239-476-2059",
    certificationType: "Graduate Gemologist",
    certifyingAuthority: "IGI",
    yearsOfExperience: 48,
    specialization: ["Diamonds", "Rubies"],
    status: "Pending Verification",
    lastVerifiedDate: "4/22/2025",
  },
  {
    id: 5,
    firstName: "Kelsey",
    lastName: "Smedmoor",
    email: "ksmedmoor4@smugmug.com",
    phoneNumber: "902-401-6817",
    certificationType: "Graduate Gemologist",
    certifyingAuthority: "IGI",
    yearsOfExperience: 43,
    specialization: ["Diamonds", "Emeralds"],
    status: "Active",
    lastVerifiedDate: "4/22/2025",
  },
  {
    id: 6,
    firstName: "Wynne",
    lastName: "Vasilechko",
    email: "wvasilechko5@shinystat.com",
    phoneNumber: "347-373-4636",
    certificationType: "Certified Appraiser",
    certifyingAuthority: "IGI",
    yearsOfExperience: 15,
    specialization: ["Emeralds", "Rubies"],
    status: "Active",
    lastVerifiedDate: "4/22/2025",
  },
  {
    id: 7,
    firstName: "Derk",
    lastName: "Beetles",
    email: "dbeetles6@alibaba.com",
    phoneNumber: "305-599-3500",
    certificationType: "Graduate Gemologist",
    certifyingAuthority: "AGS",
    yearsOfExperience: 40,
    specialization: ["Sapphires"],
    status: "Inactive",
    lastVerifiedDate: "4/22/2025",
  },
  {
    id: 8,
    firstName: "Dru",
    lastName: "Addyman",
    email: "daddyman7@is.gd",
    phoneNumber: "481-641-4495",
    certificationType: "Jewelry Designer",
    certifyingAuthority: "AGS",
    yearsOfExperience: 22,
    specialization: ["Emeralds"],
    status: "Active",
    lastVerifiedDate: "4/22/2025",
  },
  {
    id: 9,
    firstName: "Marja",
    lastName: "Purchon",
    email: "mpurchon8@studiopress.com",
    phoneNumber: "474-662-5724",
    certificationType: "Certified Appraiser",
    certifyingAuthority: "GIA",
    yearsOfExperience: 8,
    specialization: ["Diamonds"],
    status: "Active",
    lastVerifiedDate: "4/22/2025",
  },
  {
    id: 10,
    firstName: "Antonino",
    lastName: "Hubery",
    email: "ahubery9@ucla.edu",
    phoneNumber: "889-775-4172",
    certificationType: "Jewelry Designer",
    certifyingAuthority: "GIA",
    yearsOfExperience: 46,
    specialization: ["Emeralds", "Diamonds"],
    status: "Inactive",
    lastVerifiedDate: "4/22/2025",
  },
  {
    id: 11,
    firstName: "Matthiew",
    lastName: "Bedingfield",
    email: "mbedingfielda@ucsd.edu",
    phoneNumber: "443-292-9551",
    certificationType: "Graduate Gemologist",
    certifyingAuthority: "AGS",
    yearsOfExperience: 15,
    specialization: ["Emeralds"],
    status: "Active",
    lastVerifiedDate: "4/22/2025",
  },
  {
    id: 12,
    firstName: "Farris",
    lastName: "Kettow",
    email: "fkettowb@macromedia.com",
    phoneNumber: "576-951-1513",
    certificationType: "Graduate Gemologist",
    certifyingAuthority: "AGS",
    yearsOfExperience: 35,
    specialization: ["Sapphires", "Emeralds"],
    status: "Active",
    lastVerifiedDate: "4/22/2025",
  },
  {
    id: 13,
    firstName: "Ross",
    lastName: "Paskerful",
    email: "rpaskerfulc@google.co.uk",
    phoneNumber: "182-915-0242",
    certificationType: "Jewelry Designer",
    certifyingAuthority: "GIA",
    yearsOfExperience: 30,
    specialization: ["Emeralds"],
    status: "Inactive",
    lastVerifiedDate: "4/22/2025",
  },
  {
    id: 14,
    firstName: "Innis",
    lastName: "Mc Carroll",
    email: "imccarrolld@cmu.edu",
    phoneNumber: "267-323-3326",
    certificationType: "Jewelry Designer",
    certifyingAuthority: "AGS",
    yearsOfExperience: 27,
    specialization: ["Emeralds"],
    status: "Inactive",
    lastVerifiedDate: "4/22/2025",
  },
  {
    id: 15,
    firstName: "Benedict",
    lastName: "Rendbaek",
    email: "brendbaeke@tamu.edu",
    phoneNumber: "523-344-4956",
    certificationType: "Jewelry Designer",
    certifyingAuthority: "GIA",
    yearsOfExperience: 11,
    specialization: ["Rubies", "Sapphires"],
    status: "Inactive",
    lastVerifiedDate: "4/22/2025",
  },
  {
    id: 16,
    firstName: "Moishe",
    lastName: "Josse",
    email: "mjossef@shutterfly.com",
    phoneNumber: "163-372-5818",
    certificationType: "Graduate Gemologist",
    certifyingAuthority: "GIA",
    yearsOfExperience: 23,
    specialization: ["Diamonds", "Sapphires"],
    status: "Inactive",
    lastVerifiedDate: "4/22/2025",
  },
  {
    id: 17,
    firstName: "Josephine",
    lastName: "Jerrolt",
    email: "jjerroltg@shinystat.com",
    phoneNumber: "228-100-3517",
    certificationType: "Jewelry Designer",
    certifyingAuthority: "AGS",
    yearsOfExperience: 44,
    specialization: ["Emeralds"],
    status: "Pending Verification",
    lastVerifiedDate: "4/22/2025",
  },
  {
    id: 18,
    firstName: "Wilmette",
    lastName: "Dupree",
    email: "wdupreeh@ucla.edu",
    phoneNumber: "584-538-0226",
    certificationType: "Graduate Gemologist",
    certifyingAuthority: "GIA",
    yearsOfExperience: 49,
    specialization: ["Sapphires", "Emeralds"],
    status: "Pending Verification",
    lastVerifiedDate: "4/22/2025",
  },
  {
    id: 19,
    firstName: "Egor",
    lastName: "Tzarkov",
    email: "etzarkovi@time.com",
    phoneNumber: "202-355-0468",
    certificationType: "Jewelry Designer",
    certifyingAuthority: "GIA",
    yearsOfExperience: 27,
    specialization: ["Rubies"],
    status: "Pending Verification",
    lastVerifiedDate: "4/22/2025",
  },
  {
    id: 20,
    firstName: "Johnette",
    lastName: "Prest",
    email: "jprestj@admin.ch",
    phoneNumber: "842-169-1050",
    certificationType: "Graduate Gemologist",
    certifyingAuthority: "IGI",
    yearsOfExperience: 50,
    specialization: ["Rubies"],
    status: "Pending Verification",
    lastVerifiedDate: "4/22/2025",
  },
  {
    id: 21,
    firstName: "Kris",
    lastName: "Cabedo",
    email: "kcabedok@ucoz.com",
    phoneNumber: "129-148-0316",
    certificationType: "Jewelry Designer",
    certifyingAuthority: "IGI",
    yearsOfExperience: 46,
    specialization: ["Rubies", "Emeralds"],
    status: "Inactive",
    lastVerifiedDate: "4/22/2025",
  },
  {
    id: 22,
    firstName: "Brooks",
    lastName: "Menhenitt",
    email: "bmenhenittl@dailymail.co.uk",
    phoneNumber: "689-891-0866",
    certificationType: "Graduate Gemologist",
    certifyingAuthority: "GIA",
    yearsOfExperience: 31,
    specialization: ["Diamonds", "Rubies"],
    status: "Active",
    lastVerifiedDate: "4/22/2025",
  },
  {
    id: 23,
    firstName: "Abram",
    lastName: "Climson",
    email: "aclimsonm@indiatimes.com",
    phoneNumber: "197-718-0268",
    certificationType: "Jewelry Designer",
    certifyingAuthority: "IGI",
    yearsOfExperience: 6,
    specialization: ["Diamonds"],
    status: "Pending Verification",
    lastVerifiedDate: "4/22/2025",
  },
  {
    id: 24,
    firstName: "Hesther",
    lastName: "Tofful",
    email: "htoffuln@domainmarket.com",
    phoneNumber: "267-903-6303",
    certificationType: "Jewelry Designer",
    certifyingAuthority: "AGS",
    yearsOfExperience: 43,
    specialization: ["Diamonds"],
    status: "Pending Verification",
    lastVerifiedDate: "4/22/2025",
  },
  {
    id: 25,
    firstName: "Germain",
    lastName: "Marages",
    email: "gmarageso@kickstarter.com",
    phoneNumber: "273-458-4685",
    certificationType: "Jewelry Designer",
    certifyingAuthority: "IGI",
    yearsOfExperience: 14,
    specialization: ["Diamonds"],
    status: "Pending Verification",
    lastVerifiedDate: "4/22/2025",
  },
  {
    id: 26,
    firstName: "Elfrida",
    lastName: "Gange",
    email: "egangep@a8.net",
    phoneNumber: "627-276-5981",
    certificationType: "Graduate Gemologist",
    certifyingAuthority: "GIA",
    yearsOfExperience: 7,
    specialization: ["Rubies", "Sapphires"],
    status: "Active",
    lastVerifiedDate: "4/22/2025",
  },
  {
    id: 27,
    firstName: "Stavro",
    lastName: "Dudderidge",
    email: "sdudderidgeq@ihg.com",
    phoneNumber: "689-352-1857",
    certificationType: "Jewelry Designer",
    certifyingAuthority: "IGI",
    yearsOfExperience: 20,
    specialization: ["Rubies", "Sapphires"],
    status: "Active",
    lastVerifiedDate: "4/22/2025",
  },
  {
    id: 28,
    firstName: "Audie",
    lastName: "Isbell",
    email: "aisbellr@cloudflare.com",
    phoneNumber: "440-373-8181",
    certificationType: "Certified Appraiser",
    certifyingAuthority: "IGI",
    yearsOfExperience: 6,
    specialization: ["Diamonds"],
    status: "Active",
    lastVerifiedDate: "4/22/2025",
  },
  {
    id: 29,
    firstName: "Mureil",
    lastName: "Buckerfield",
    email: "mbuckerfields@psu.edu",
    phoneNumber: "146-553-3948",
    certificationType: "Certified Appraiser",
    certifyingAuthority: "IGI",
    yearsOfExperience: 15,
    specialization: ["Sapphires"],
    status: "Pending Verification",
    lastVerifiedDate: "4/22/2025",
  },
  {
    id: 30,
    firstName: "Jeniffer",
    lastName: "Presser",
    email: "jpressert@hc360.com",
    phoneNumber: "152-305-6205",
    certificationType: "Graduate Gemologist",
    certifyingAuthority: "AGS",
    yearsOfExperience: 20,
    specialization: ["Rubies"],
    status: "Active",
    lastVerifiedDate: "4/22/2025",
  },
  {
    id: 31,
    firstName: "Bryn",
    lastName: "Gaudin",
    email: "bgaudinu@bizjournals.com",
    phoneNumber: "385-948-1638",
    certificationType: "Certified Appraiser",
    certifyingAuthority: "GIA",
    yearsOfExperience: 37,
    specialization: ["Sapphires"],
    status: "Pending Verification",
    lastVerifiedDate: "4/22/2025",
  },
  {
    id: 32,
    firstName: "Estrella",
    lastName: "Dahlberg",
    email: "edahlbergv@smh.com.au",
    phoneNumber: "147-194-7771",
    certificationType: "Graduate Gemologist",
    certifyingAuthority: "IGI",
    yearsOfExperience: 7,
    specialization: ["Emeralds"],
    status: "Active",
    lastVerifiedDate: "4/22/2025",
  },
  {
    id: 33,
    firstName: "Donnajean",
    lastName: "Castilla",
    email: "dcastillaw@furl.net",
    phoneNumber: "669-662-2766",
    certificationType: "Jewelry Designer",
    certifyingAuthority: "GIA",
    yearsOfExperience: 17,
    specialization: ["Emeralds"],
    status: "Pending Verification",
    lastVerifiedDate: "4/22/2025",
  },
  {
    id: 34,
    firstName: "Hazel",
    lastName: "Tattersall",
    email: "htattersallx@topsy.com",
    phoneNumber: "612-646-2597",
    certificationType: "Certified Appraiser",
    certifyingAuthority: "AGS",
    yearsOfExperience: 25,
    specialization: ["Diamonds", "Sapphires"],
    status: "Pending Verification",
    lastVerifiedDate: "4/22/2025",
  },
  {
    id: 35,
    firstName: "Lisetta",
    lastName: "Castell",
    email: "lcastelly@fema.gov",
    phoneNumber: "430-898-1453",
    certificationType: "Jewelry Designer",
    certifyingAuthority: "GIA",
    yearsOfExperience: 45,
    specialization: ["Emeralds"],
    status: "Active",
    lastVerifiedDate: "4/22/2025",
  },
  {
    id: 36,
    firstName: "Ursula",
    lastName: "Grint",
    email: "ugrintz@pen.io",
    phoneNumber: "163-562-9895",
    certificationType: "Jewelry Designer",
    certifyingAuthority: "AGS",
    yearsOfExperience: 7,
    specialization: ["Emeralds", "Diamonds"],
    status: "Active",
    lastVerifiedDate: "4/22/2025",
  },
  {
    id: 37,
    firstName: "Ora",
    lastName: "Jenny",
    email: "ojenny10@mashable.com",
    phoneNumber: "614-387-4190",
    certificationType: "Jewelry Designer",
    certifyingAuthority: "AGS",
    yearsOfExperience: 10,
    specialization: ["Emeralds", "Sapphires"],
    status: "Inactive",
    lastVerifiedDate: "4/22/2025",
  },
  {
    id: 38,
    firstName: "Stanfield",
    lastName: "Peirson",
    email: "speirson11@artisteer.com",
    phoneNumber: "755-625-4411",
    certificationType: "Graduate Gemologist",
    certifyingAuthority: "IGI",
    yearsOfExperience: 8,
    specialization: ["Diamonds"],
    status: "Pending Verification",
    lastVerifiedDate: "4/22/2025",
  },
  {
    id: 39,
    firstName: "Glynda",
    lastName: "Fraczkiewicz",
    email: "gfraczkiewicz12@dailymail.co.uk",
    phoneNumber: "931-421-0238",
    certificationType: "Jewelry Designer",
    certifyingAuthority: "GIA",
    yearsOfExperience: 26,
    specialization: ["Sapphires", "Emeralds"],
    status: "Active",
    lastVerifiedDate: "4/22/2025",
  },
  {
    id: 40,
    firstName: "Teddie",
    lastName: "Vagges",
    email: "tvagges13@hp.com",
    phoneNumber: "827-681-5028",
    certificationType: "Graduate Gemologist",
    certifyingAuthority: "GIA",
    yearsOfExperience: 37,
    specialization: ["Diamonds", "Rubies"],
    status: "Pending Verification",
    lastVerifiedDate: "4/22/2025",
  },
  {
    id: 41,
    firstName: "Dickie",
    lastName: "Benedtti",
    email: "dbenedtti14@ovh.net",
    phoneNumber: "652-243-2935",
    certificationType: "Certified Appraiser",
    certifyingAuthority: "IGI",
    yearsOfExperience: 31,
    specialization: ["Sapphires"],
    status: "Inactive",
    lastVerifiedDate: "4/22/2025",
  },
  {
    id: 42,
    firstName: "Ashley",
    lastName: "Devitt",
    email: "adevitt15@mlb.com",
    phoneNumber: "473-581-8301",
    certificationType: "Jewelry Designer",
    certifyingAuthority: "IGI",
    yearsOfExperience: 5,
    specialization: ["Emeralds"],
    status: "Active",
    lastVerifiedDate: "4/22/2025",
  },
  {
    id: 43,
    firstName: "Tobi",
    lastName: "Geill",
    email: "tgeill16@typepad.com",
    phoneNumber: "925-714-9809",
    certificationType: "Certified Appraiser",
    certifyingAuthority: "IGI",
    yearsOfExperience: 45,
    specialization: ["Diamonds", "Rubies"],
    status: "Pending Verification",
    lastVerifiedDate: "4/22/2025",
  },
  {
    id: 44,
    firstName: "Gabriello",
    lastName: "Morbey",
    email: "gmorbey17@google.com.au",
    phoneNumber: "950-938-1968",
    certificationType: "Jewelry Designer",
    certifyingAuthority: "GIA",
    yearsOfExperience: 12,
    specialization: ["Sapphires"],
    status: "Inactive",
    lastVerifiedDate: "4/22/2025",
  },
  {
    id: 45,
    firstName: "Aguste",
    lastName: "Hurrion",
    email: "ahurrion18@so-net.ne.jp",
    phoneNumber: "797-531-0797",
    certificationType: "Graduate Gemologist",
    certifyingAuthority: "GIA",
    yearsOfExperience: 1,
    specialization: ["Diamonds"],
    status: "Active",
    lastVerifiedDate: "4/22/2025",
  },
  {
    id: 46,
    firstName: "Hallie",
    lastName: "Kynd",
    email: "hkynd19@marriott.com",
    phoneNumber: "215-548-6826",
    certificationType: "Graduate Gemologist",
    certifyingAuthority: "AGS",
    yearsOfExperience: 35,
    specialization: ["Emeralds"],
    status: "Active",
    lastVerifiedDate: "4/22/2025",
  },
  {
    id: 47,
    firstName: "Fanny",
    lastName: "Filippozzi",
    email: "ffilippozzi1a@disqus.com",
    phoneNumber: "258-334-0220",
    certificationType: "Certified Appraiser",
    certifyingAuthority: "IGI",
    yearsOfExperience: 40,
    specialization: ["Rubies"],
    status: "Inactive",
    lastVerifiedDate: "4/22/2025",
  },
  {
    id: 48,
    firstName: "Sigismund",
    lastName: "Morecomb",
    email: "smorecomb1b@csmonitor.com",
    phoneNumber: "281-837-8628",
    certificationType: "Graduate Gemologist",
    certifyingAuthority: "IGI",
    yearsOfExperience: 33,
    specialization: ["Emeralds"],
    status: "Inactive",
    lastVerifiedDate: "4/22/2025",
  },
  {
    id: 49,
    firstName: "Boone",
    lastName: "Pyper",
    email: "bpyper1c@dion.ne.jp",
    phoneNumber: "842-690-0500",
    certificationType: "Jewelry Designer",
    certifyingAuthority: "AGS",
    yearsOfExperience: 14,
    specialization: ["Diamonds"],
    status: "Active",
    lastVerifiedDate: "4/22/2025",
  },
  {
    id: 50,
    firstName: "Bess",
    lastName: "Pill",
    email: "bpill1d@bbb.org",
    phoneNumber: "644-613-5926",
    certificationType: "Jewelry Designer",
    certifyingAuthority: "GIA",
    yearsOfExperience: 50,
    specialization: ["Diamonds"],
    status: "Inactive",
    lastVerifiedDate: "4/22/2025",
  },
  {
    id: 51,
    firstName: "Shawn",
    lastName: "Barhem",
    email: "sbarhem1e@usa.gov",
    phoneNumber: "371-323-2214",
    certificationType: "Graduate Gemologist",
    certifyingAuthority: "GIA",
    yearsOfExperience: 16,
    specialization: ["Diamonds"],
    status: "Active",
    lastVerifiedDate: "4/22/2025",
  },
  {
    id: 52,
    firstName: "Benson",
    lastName: "Lightoller",
    email: "blightoller1f@google.co.uk",
    phoneNumber: "408-288-5485",
    certificationType: "Certified Appraiser",
    certifyingAuthority: "GIA",
    yearsOfExperience: 29,
    specialization: ["Rubies"],
    status: "Active",
    lastVerifiedDate: "4/22/2025",
  },
  {
    id: 53,
    firstName: "Lesya",
    lastName: "Bagg",
    email: "lbagg1g@springer.com",
    phoneNumber: "610-827-2788",
    certificationType: "Certified Appraiser",
    certifyingAuthority: "AGS",
    yearsOfExperience: 48,
    specialization: ["Sapphires"],
    status: "Pending Verification",
    lastVerifiedDate: "4/22/2025",
  },
  {
    id: 54,
    firstName: "Tani",
    lastName: "Jarvie",
    email: "tjarvie1h@about.me",
    phoneNumber: "430-465-9074",
    certificationType: "Certified Appraiser",
    certifyingAuthority: "GIA",
    yearsOfExperience: 2,
    specialization: ["Emeralds", "Sapphires"],
    status: "Pending Verification",
    lastVerifiedDate: "4/22/2025",
  },
  {
    id: 55,
    firstName: "Scarlett",
    lastName: "Mallon",
    email: "smallon1i@rakuten.co.jp",
    phoneNumber: "796-945-3013",
    certificationType: "Jewelry Designer",
    certifyingAuthority: "GIA",
    yearsOfExperience: 41,
    specialization: ["Diamonds", "Emeralds"],
    status: "Pending Verification",
    lastVerifiedDate: "4/22/2025",
  },
  {
    id: 56,
    firstName: "Clayton",
    lastName: "Gillie",
    email: "cgillie1j@virginia.edu",
    phoneNumber: "383-404-0630",
    certificationType: "Jewelry Designer",
    certifyingAuthority: "IGI",
    yearsOfExperience: 33,
    specialization: ["Sapphires", "Emeralds"],
    status: "Inactive",
    lastVerifiedDate: "4/22/2025",
  },
  {
    id: 57,
    firstName: "Margalo",
    lastName: "Bootland",
    email: "mbootland1k@geocities.jp",
    phoneNumber: "374-644-3943",
    certificationType: "Certified Appraiser",
    certifyingAuthority: "IGI",
    yearsOfExperience: 40,
    specialization: ["Emeralds", "Rubies"],
    status: "Pending Verification",
    lastVerifiedDate: "4/22/2025",
  },
  {
    id: 58,
    firstName: "Skye",
    lastName: "Cottey",
    email: "scottey1l@123-reg.co.uk",
    phoneNumber: "431-561-4254",
    certificationType: "Jewelry Designer",
    certifyingAuthority: "IGI",
    yearsOfExperience: 27,
    specialization: ["Sapphires"],
    status: "Inactive",
    lastVerifiedDate: "4/22/2025",
  },
  {
    id: 59,
    firstName: "Gilemette",
    lastName: "Gammidge",
    email: "ggammidge1m@github.io",
    phoneNumber: "742-352-7344",
    certificationType: "Jewelry Designer",
    certifyingAuthority: "IGI",
    yearsOfExperience: 9,
    specialization: ["Sapphires"],
    status: "Pending Verification",
    lastVerifiedDate: "4/22/2025",
  },
  {
    id: 60,
    firstName: "Mela",
    lastName: "Briggdale",
    email: "mbriggdale1n@ebay.com",
    phoneNumber: "731-398-8544",
    certificationType: "Jewelry Designer",
    certifyingAuthority: "AGS",
    yearsOfExperience: 46,
    specialization: ["Sapphires", "Rubies"],
    status: "Active",
    lastVerifiedDate: "4/22/2025",
  },
  {
    id: 61,
    firstName: "Gianna",
    lastName: "Cutchee",
    email: "gcutchee1o@rediff.com",
    phoneNumber: "614-340-1012",
    certificationType: "Graduate Gemologist",
    certifyingAuthority: "GIA",
    yearsOfExperience: 33,
    specialization: ["Rubies"],
    status: "Inactive",
    lastVerifiedDate: "4/22/2025",
  },
  {
    id: 62,
    firstName: "Dewey",
    lastName: "Burdin",
    email: "dburdin1p@addtoany.com",
    phoneNumber: "959-163-8113",
    certificationType: "Certified Appraiser",
    certifyingAuthority: "GIA",
    yearsOfExperience: 10,
    specialization: ["Rubies", "Sapphires"],
    status: "Active",
    lastVerifiedDate: "4/22/2025",
  },
  {
    id: 63,
    firstName: "Kacy",
    lastName: "Le Clercq",
    email: "kleclercq1q@biglobe.ne.jp",
    phoneNumber: "267-149-5886",
    certificationType: "Certified Appraiser",
    certifyingAuthority: "GIA",
    yearsOfExperience: 34,
    specialization: ["Emeralds", "Diamonds"],
    status: "Pending Verification",
    lastVerifiedDate: "4/22/2025",
  },
  {
    id: 64,
    firstName: "Casandra",
    lastName: "Dunridge",
    email: "cdunridge1r@ted.com",
    phoneNumber: "315-276-7452",
    certificationType: "Jewelry Designer",
    certifyingAuthority: "IGI",
    yearsOfExperience: 49,
    specialization: ["Diamonds", "Emeralds"],
    status: "Pending Verification",
    lastVerifiedDate: "4/22/2025",
  },
  {
    id: 65,
    firstName: "Mata",
    lastName: "Kisar",
    email: "mkisar1s@apache.org",
    phoneNumber: "673-353-1903",
    certificationType: "Jewelry Designer",
    certifyingAuthority: "GIA",
    yearsOfExperience: 28,
    specialization: ["Sapphires"],
    status: "Active",
    lastVerifiedDate: "4/22/2025",
  },
  {
    id: 66,
    firstName: "Arabelle",
    lastName: "Shorthill",
    email: "ashorthill1t@smugmug.com",
    phoneNumber: "771-275-7001",
    certificationType: "Graduate Gemologist",
    certifyingAuthority: "AGS",
    yearsOfExperience: 32,
    specialization: ["Rubies", "Emeralds"],
    status: "Inactive",
    lastVerifiedDate: "4/22/2025",
  },
  {
    id: 67,
    firstName: "Rees",
    lastName: "Abramzon",
    email: "rabramzon1u@creativecommons.org",
    phoneNumber: "951-925-5337",
    certificationType: "Certified Appraiser",
    certifyingAuthority: "GIA",
    yearsOfExperience: 2,
    specialization: ["Diamonds"],
    status: "Active",
    lastVerifiedDate: "4/22/2025",
  },
  {
    id: 68,
    firstName: "Byron",
    lastName: "Perkin",
    email: "bperkin1v@gizmodo.com",
    phoneNumber: "154-907-4906",
    certificationType: "Certified Appraiser",
    certifyingAuthority: "GIA",
    yearsOfExperience: 23,
    specialization: ["Sapphires"],
    status: "Pending Verification",
    lastVerifiedDate: "4/22/2025",
  },
  {
    id: 69,
    firstName: "Leoine",
    lastName: "Harriagn",
    email: "lharriagn1w@shutterfly.com",
    phoneNumber: "449-308-9095",
    certificationType: "Certified Appraiser",
    certifyingAuthority: "IGI",
    yearsOfExperience: 39,
    specialization: ["Rubies", "Diamonds"],
    status: "Pending Verification",
    lastVerifiedDate: "4/22/2025",
  },
  {
    id: 70,
    firstName: "Neddy",
    lastName: "Beacom",
    email: "nbeacom1x@washington.edu",
    phoneNumber: "450-723-5150",
    certificationType: "Certified Appraiser",
    certifyingAuthority: "AGS",
    yearsOfExperience: 18,
    specialization: ["Rubies", "Sapphires"],
    status: "Pending Verification",
    lastVerifiedDate: "4/22/2025",
  },
  {
    id: 71,
    firstName: "Worthy",
    lastName: "Coxen",
    email: "wcoxen1y@oaic.gov.au",
    phoneNumber: "386-744-4693",
    certificationType: "Jewelry Designer",
    certifyingAuthority: "AGS",
    yearsOfExperience: 45,
    specialization: ["Sapphires", "Emeralds"],
    status: "Active",
    lastVerifiedDate: "4/22/2025",
  },
  {
    id: 72,
    firstName: "Patrice",
    lastName: "Sallier",
    email: "psallier1z@cyberchimps.com",
    phoneNumber: "839-273-4323",
    certificationType: "Graduate Gemologist",
    certifyingAuthority: "AGS",
    yearsOfExperience: 30,
    specialization: ["Emeralds"],
    status: "Pending Verification",
    lastVerifiedDate: "4/22/2025",
  },
  {
    id: 73,
    firstName: "Colline",
    lastName: "MacWhirter",
    email: "cmacwhirter20@cbslocal.com",
    phoneNumber: "817-598-9988",
    certificationType: "Graduate Gemologist",
    certifyingAuthority: "GIA",
    yearsOfExperience: 31,
    specialization: ["Rubies"],
    status: "Active",
    lastVerifiedDate: "4/22/2025",
  },
  {
    id: 74,
    firstName: "Toiboid",
    lastName: "Piddick",
    email: "tpiddick21@prnewswire.com",
    phoneNumber: "620-230-6726",
    certificationType: "Graduate Gemologist",
    certifyingAuthority: "AGS",
    yearsOfExperience: 46,
    specialization: ["Rubies", "Emeralds"],
    status: "Inactive",
    lastVerifiedDate: "4/22/2025",
  },
  {
    id: 75,
    firstName: "Kara-lynn",
    lastName: "Van Schafflaer",
    email: "kvanschafflaer22@alibaba.com",
    phoneNumber: "136-561-8780",
    certificationType: "Certified Appraiser",
    certifyingAuthority: "AGS",
    yearsOfExperience: 28,
    specialization: ["Sapphires", "Diamonds"],
    status: "Active",
    lastVerifiedDate: "4/22/2025",
  },
  {
    id: 76,
    firstName: "Shannon",
    lastName: "Luesley",
    email: "sluesley23@aol.com",
    phoneNumber: "673-922-2720",
    certificationType: "Graduate Gemologist",
    certifyingAuthority: "GIA",
    yearsOfExperience: 5,
    specialization: ["Emeralds"],
    status: "Active",
    lastVerifiedDate: "4/22/2025",
  },
  {
    id: 77,
    firstName: "Melessa",
    lastName: "Ivancevic",
    email: "mivancevic24@auda.org.au",
    phoneNumber: "946-355-3415",
    certificationType: "Graduate Gemologist",
    certifyingAuthority: "GIA",
    yearsOfExperience: 40,
    specialization: ["Diamonds"],
    status: "Pending Verification",
    lastVerifiedDate: "4/22/2025",
  },
  {
    id: 78,
    firstName: "Edita",
    lastName: "Preshaw",
    email: "epreshaw25@wordpress.com",
    phoneNumber: "963-804-6476",
    certificationType: "Certified Appraiser",
    certifyingAuthority: "IGI",
    yearsOfExperience: 48,
    specialization: ["Emeralds"],
    status: "Inactive",
    lastVerifiedDate: "4/22/2025",
  },
  {
    id: 79,
    firstName: "Adela",
    lastName: "Banville",
    email: "abanville26@un.org",
    phoneNumber: "558-655-8402",
    certificationType: "Graduate Gemologist",
    certifyingAuthority: "GIA",
    yearsOfExperience: 46,
    specialization: ["Diamonds"],
    status: "Pending Verification",
    lastVerifiedDate: "4/22/2025",
  },
  {
    id: 80,
    firstName: "Bordie",
    lastName: "Highway",
    email: "bhighway27@timesonline.co.uk",
    phoneNumber: "624-980-8652",
    certificationType: "Jewelry Designer",
    certifyingAuthority: "GIA",
    yearsOfExperience: 27,
    specialization: ["Emeralds", "Sapphires"],
    status: "Pending Verification",
    lastVerifiedDate: "4/22/2025",
  },
  {
    id: 81,
    firstName: "Roshelle",
    lastName: "Whiteson",
    email: "rwhiteson28@ucsd.edu",
    phoneNumber: "427-928-7321",
    certificationType: "Certified Appraiser",
    certifyingAuthority: "AGS",
    yearsOfExperience: 46,
    specialization: ["Diamonds", "Sapphires"],
    status: "Pending Verification",
    lastVerifiedDate: "4/22/2025",
  },
  {
    id: 82,
    firstName: "Rosella",
    lastName: "Demko",
    email: "rdemko29@wsj.com",
    phoneNumber: "158-716-4676",
    certificationType: "Certified Appraiser",
    certifyingAuthority: "GIA",
    yearsOfExperience: 26,
    specialization: ["Rubies", "Diamonds"],
    status: "Inactive",
    lastVerifiedDate: "4/22/2025",
  },
  {
    id: 83,
    firstName: "Aylmer",
    lastName: "Yuryshev",
    email: "ayuryshev2a@xing.com",
    phoneNumber: "689-777-1109",
    certificationType: "Certified Appraiser",
    certifyingAuthority: "IGI",
    yearsOfExperience: 1,
    specialization: ["Rubies"],
    status: "Inactive",
    lastVerifiedDate: "4/22/2025",
  },
  {
    id: 84,
    firstName: "Katinka",
    lastName: "Charer",
    email: "kcharer2b@google.ca",
    phoneNumber: "689-479-5877",
    certificationType: "Certified Appraiser",
    certifyingAuthority: "IGI",
    yearsOfExperience: 35,
    specialization: ["Emeralds"],
    status: "Active",
    lastVerifiedDate: "4/22/2025",
  },
  {
    id: 85,
    firstName: "Godart",
    lastName: "Stuckley",
    email: "gstuckley2c@discovery.com",
    phoneNumber: "345-748-0909",
    certificationType: "Jewelry Designer",
    certifyingAuthority: "IGI",
    yearsOfExperience: 9,
    specialization: ["Rubies", "Emeralds"],
    status: "Inactive",
    lastVerifiedDate: "4/22/2025",
  },
  {
    id: 86,
    firstName: "Marleen",
    lastName: "Stubs",
    email: "mstubs2d@is.gd",
    phoneNumber: "670-281-5675",
    certificationType: "Jewelry Designer",
    certifyingAuthority: "AGS",
    yearsOfExperience: 31,
    specialization: ["Diamonds", "Sapphires"],
    status: "Inactive",
    lastVerifiedDate: "4/22/2025",
  },
  {
    id: 87,
    firstName: "Fletch",
    lastName: "Bligh",
    email: "fbligh2e@sourceforge.net",
    phoneNumber: "168-289-8327",
    certificationType: "Certified Appraiser",
    certifyingAuthority: "AGS",
    yearsOfExperience: 33,
    specialization: ["Sapphires", "Emeralds"],
    status: "Active",
    lastVerifiedDate: "4/22/2025",
  },
  {
    id: 88,
    firstName: "Lind",
    lastName: "Gething",
    email: "lgething2f@arstechnica.com",
    phoneNumber: "970-534-6095",
    certificationType: "Jewelry Designer",
    certifyingAuthority: "AGS",
    yearsOfExperience: 1,
    specialization: ["Emeralds", "Diamonds"],
    status: "Inactive",
    lastVerifiedDate: "4/22/2025",
  },
  {
    id: 89,
    firstName: "Hestia",
    lastName: "Milington",
    email: "hmilington2g@w3.org",
    phoneNumber: "414-667-2577",
    certificationType: "Graduate Gemologist",
    certifyingAuthority: "AGS",
    yearsOfExperience: 5,
    specialization: ["Rubies", "Sapphires"],
    status: "Active",
    lastVerifiedDate: "4/22/2025",
  },
  {
    id: 90,
    firstName: "Stanislaw",
    lastName: "Esplin",
    email: "sesplin2h@google.ca",
    phoneNumber: "183-939-2717",
    certificationType: "Jewelry Designer",
    certifyingAuthority: "GIA",
    yearsOfExperience: 31,
    specialization: ["Sapphires"],
    status: "Active",
    lastVerifiedDate: "4/22/2025",
  },
  {
    id: 91,
    firstName: "Lanny",
    lastName: "Milligan",
    email: "lmilligan2i@adobe.com",
    phoneNumber: "212-247-6616",
    certificationType: "Certified Appraiser",
    certifyingAuthority: "GIA",
    yearsOfExperience: 2,
    specialization: ["Diamonds", "Emeralds"],
    status: "Active",
    lastVerifiedDate: "4/22/2025",
  },
  {
    id: 92,
    firstName: "Leontyne",
    lastName: "Clayton",
    email: "lclayton2j@army.mil",
    phoneNumber: "413-927-6917",
    certificationType: "Jewelry Designer",
    certifyingAuthority: "AGS",
    yearsOfExperience: 14,
    specialization: ["Rubies"],
    status: "Active",
    lastVerifiedDate: "4/22/2025",
  },
  {
    id: 93,
    firstName: "Blancha",
    lastName: "Golsworthy",
    email: "bgolsworthy2k@wisc.edu",
    phoneNumber: "447-381-1110",
    certificationType: "Certified Appraiser",
    certifyingAuthority: "GIA",
    yearsOfExperience: 48,
    specialization: ["Emeralds"],
    status: "Inactive",
    lastVerifiedDate: "4/22/2025",
  },
  {
    id: 94,
    firstName: "Glad",
    lastName: "McDonand",
    email: "gmcdonand2l@usnews.com",
    phoneNumber: "484-364-2101",
    certificationType: "Jewelry Designer",
    certifyingAuthority: "GIA",
    yearsOfExperience: 11,
    specialization: ["Diamonds"],
    status: "Inactive",
    lastVerifiedDate: "4/22/2025",
  },
  {
    id: 95,
    firstName: "Nadia",
    lastName: "Dawney",
    email: "ndawney2m@wsj.com",
    phoneNumber: "876-914-2136",
    certificationType: "Certified Appraiser",
    certifyingAuthority: "AGS",
    yearsOfExperience: 12,
    specialization: ["Emeralds", "Diamonds"],
    status: "Pending Verification",
    lastVerifiedDate: "4/22/2025",
  },
  {
    id: 96,
    firstName: "Normy",
    lastName: "Pylkynyton",
    email: "npylkynyton2n@posterous.com",
    phoneNumber: "611-790-4229",
    certificationType: "Certified Appraiser",
    certifyingAuthority: "GIA",
    yearsOfExperience: 1,
    specialization: ["Diamonds"],
    status: "Active",
    lastVerifiedDate: "4/22/2025",
  },
  {
    id: 97,
    firstName: "William",
    lastName: "Stovell",
    email: "wstovell2o@cocolog-nifty.com",
    phoneNumber: "168-335-7575",
    certificationType: "Graduate Gemologist",
    certifyingAuthority: "GIA",
    yearsOfExperience: 13,
    specialization: ["Emeralds", "Sapphires"],
    status: "Pending Verification",
    lastVerifiedDate: "4/22/2025",
  },
  {
    id: 98,
    firstName: "Kirsten",
    lastName: "Gibbons",
    email: "kgibbons2p@sohu.com",
    phoneNumber: "625-932-1099",
    certificationType: "Certified Appraiser",
    certifyingAuthority: "AGS",
    yearsOfExperience: 39,
    specialization: ["Rubies"],
    status: "Active",
    lastVerifiedDate: "4/22/2025",
  },
  {
    id: 99,
    firstName: "Charmion",
    lastName: "Gately",
    email: "cgately2q@eventbrite.com",
    phoneNumber: "754-511-1383",
    certificationType: "Certified Appraiser",
    certifyingAuthority: "IGI",
    yearsOfExperience: 24,
    specialization: ["Diamonds"],
    status: "Active",
    lastVerifiedDate: "4/22/2025",
  },
  {
    id: 100,
    firstName: "Christoph",
    lastName: "Leward",
    email: "cleward2r@discuz.net",
    phoneNumber: "303-749-9221",
    certificationType: "Jewelry Designer",
    certifyingAuthority: "IGI",
    yearsOfExperience: 31,
    specialization: ["Rubies", "Diamonds"],
    status: "Active",
    lastVerifiedDate: "4/22/2025",
  },
];
const EndoserPage = () => {
  const [open, setOpen] = React.useState<boolean>(false);
  const [rows, setRows] = React.useState<any[]>(endoserdata);

  //   const { detailCards } = useSelector((state) => state.user);
  const [rowValue, setRowValue] = React.useState(null);

  //   React.useEffect(() => {
  //     setUsers(detailCards);
  //   }, [detailCards]);

  React.useEffect(() => {
    dispatch(getDetailCards());
  }, []);

  return (
    <MainCard content={false}>
      {/* filter section */}
      <CardContent>
        <EndoserTableFilter {...{ rows, setRows }} />
      </CardContent>

      {/* table */}
      <Box display={open ? "flex" : "block"}>
        <Grid container sx={{ position: "relative" }}>
          <Grid size={{ sm: open ? 5 : 12, xs: 12 }}>
            <TableProvider>
              <GenericTable
                open={open}
                setOpen={setOpen}
                data={rows}
                setRowValue={setRowValue}
                HeaderComponent={EndoserTableHeader}
                BodyComponent={EndoserTableRows}
              />
            </TableProvider>
          </Grid>
          <Grid
            size={{ sm: open ? 7 : 12, xs: 12 }}
            sx={{ borderLeft: "1px solid", borderLeftColor: "divider" }}
          >
            <CustomDrawer open={open} setOpen={setOpen} rowValue={rowValue!}>
              <EndoserDetails rowValue={rowValue!} />
            </CustomDrawer>
          </Grid>
        </Grid>
      </Box>
    </MainCard>
  );
};

export default EndoserPage;
