/*
  Warnings:

  - The values [ACCEPTED,REJECTED,AVIALABLE] on the enum `GEMSTONE_STATUS` will be removed. If these variants are still used in the database, this will fail.

*/
-- AlterEnum
BEGIN;
CREATE TYPE "GEMSTONE_STATUS_new" AS ENUM ('AVAILABLE', 'PENDING', 'SOLD');
ALTER TABLE "Gemstone" ALTER COLUMN "status" DROP DEFAULT;
ALTER TABLE "Gemstone" ALTER COLUMN "status" TYPE "GEMSTONE_STATUS_new" USING ("status"::text::"GEMSTONE_STATUS_new");
ALTER TYPE "GEMSTONE_STATUS" RENAME TO "GEMSTONE_STATUS_old";
ALTER TYPE "GEMSTONE_STATUS_new" RENAME TO "GEMSTONE_STATUS";
DROP TYPE "GEMSTONE_STATUS_old";
ALTER TABLE "Gemstone" ALTER COLUMN "status" SET DEFAULT 'PENDING';
COMMIT;
